- .github/workflows/build.yml
- cmake/FindPostgreSQL.cmake
Solution: start using CI via GitHub Actions
> Problem: unclear if it builds from clean set-up

- extensions/omni_containers/expected/container.out
- extensions/omni_containers/omni_containers--0.1.sql
- extensions/omni_containers/omni_containers.c
- extensions/omni_containers/sql/container.sql
Solution: allow passing options to docker_container_create
> Problem: can't configure Containers

- CMakeLists.txt
- extensions/omni_containers/CMakeLists.txt
- extensions/omni_containers/omni_containers.c
- libpgext/CMakeLists.txt
- libpgext/libpgext.c
- libpgext/libpgext.h
It requires explanation for what's going on, there's a lot to type. Something can go wrong.
Solution: extract this pattern as a macro
> Problem: temporary memory context may be a bit fragile

- cmake/FindPostgreSQL.cmake
- cmake/FramaC.cmake
- libgluepg_curl/CMakeLists.txt
- libgluepg_curl/libgluepg_curl.c
- libpgext/libpgext/framac.h
Solution: try employing formal verification to prove its properties
I am not very good at Frama-C, so take this with a grain of salt. It's
more for my curiosity at this point, but I'd love to see this evolve.
Also, be aware that it takes considerable amount of time to write anything
like this, so it should be used sparingly in some critical code paths.
> Problem: some code is hard to test to ensure its validity

- extensions/omni_containers/omni_containers.c
- libpgaug/CMakeLists.txt
- libpgaug/libpgaug.h
- libpgaug/libpgaug_test/CMakeLists.txt
- libpgaug/libpgaug_test/expected/memcxt.out
- libpgaug/libpgaug_test/libpgaug_test--0.1.sql
- libpgaug/libpgaug_test/libpgaug_test.c
- libpgaug/libpgaug_test/sql/memcxt.sql
Solution: design a macro that has a more natural flow to it
It also ensures temp memory context always deleted, even if we use return.
> Problem: WITH_MEMCXT macro is not very intuitive

- .github/workflows/build.yml
- README.md
- cmake/FindPostgreSQL.cmake
- extensions/omni_containers/log/initdb.log
- extensions/omni_containers/log/postmaster.log
- extensions/omni_containers/results/container.out
- extensions/omni_containers/results/images.out
- libpgaug/libpgaug_test/log/initdb.log
- libpgaug/libpgaug_test/log/postmaster.log
- libpgaug/libpgaug_test/results/memcxt.out
It's just taking time to set up PostgreSQL instances
Solution: run them in parallel so that time is not wasted
> Problem: running tests can get slow

- .clang-format
- extensions/omni_containers/omni_containers.c
- libgluepg_curl/libgluepg_curl.c
- libgluepg_yyjson/libgluepg_yyjson.c
Solution: increase column limit to 100
The monitors are wide these days, generally speaking.
I thought of going to 120, but the difference was not as striking
and some lines were getting a bit long.
> Problem: narrow code gets harder to read

- docker/builder/Dockerfile
Solution: install tmux and debuggers to make life better
> Problem: debugging in Docker container

- .github/workflows/build.yml
- cmake/FindCURL.cmake
- cmake/OpenSSL.cmake
- extensions/omni_containers/omni_containers.c
Solution: use the correct OS for macOS
> Problem: all CI runs on Linux, even macOS one

- .github/workflows/build.yml
Solution: ensure homebrew doesn't try to do too much
> Problem: spontaneous macos build failures (failing to install OpenSSL)

- extensions/omni_ext/omni_ext.c
It allocates an arbitrarily big buffer, and uses fgets/sscanf to
iterate over entries. Just way too complicated.
Solution: use fscanf and NAME_MAX constant to limit the path buffer
This also eliminates the need to have a line buffer.
> Problem: find_absolute_library_path code is not great

- extensions/omni_httpd/http_worker.c
When running a slightly more involved test (requests being logged
into a table), getting just a few of these errors:
```
cannot apply ResourceOwnerto non-saved cached plan
```
Solution: don't run event loop when removing socket
My guess is that we were getting handler invocation with inconsistent
listener contexts in some cases.
While at it, do more error checking and cleaup with regards to prepared
statements.
> Problem: getting a few spurious errors with omni_httpd

- extensions/omni_sql/expected/deparse.out
- extensions/omni_sql/omni_sql.c
- extensions/omni_sql/sql/deparse.sql
Solution: don't use stack pointers for WithClause
Also, while at it, fix the smoke test.
> Problem: omni_sql tests fail in Release mode

- .github/workflows/build.yml
Solution: run CI in both Debug & Release
Closes #48
> Problem: Debug-mode tests don't always catch all errors

- .github/workflows/clang-format.yml
- CMakeLists.txt
- extensions/omni_ext/init.c
- extensions/omni_ext/omni_ext.h
- extensions/omni_httpd/http_worker.c
- extensions/omni_httpd/master_worker.c
- extensions/omni_sql/deparse_13.c
- extensions/omni_sql/deparse_14.c
- extensions/omni_sql/deparse_15.c
- libgluepg_curl/libgluepg_curl.c
- libgluepg_curl/libgluepg_curl.h
- libgluepg_yyjson/libgluepg_yyjson.c
- libpgaug/libpgaug.c
- libpgaug/libpgaug.h
While I had the highest hope in my editor applying formatter consistently, it didn't quite happen.
Solution: ensure formatting on CI and provide a build-time task (`format`/`fix-format`)
> Problem: lost formatting

- extensions/omni_ext/workers.c
This means that for every database, it'll wait until the worker is started to start the next one.
Solution: ensure we're not blocked on this
> Problem: omni_ext waits for database worker startup

- extensions/omni_httpd/http_worker.c
- extensions/omni_httpd/http_worker.h
It's hard to read and follow the logic of it
Solution: try to re-organize it a bit
The general idea here is to put things into something closer to the order of the execution: worker process, server initialization, request handling.
It's not yet perfect but hopefully will make it a bit easier to navigate.
> Problem: omni_httpd's http_worker flow is confusing

- extensions/omni_httpd/fd.c
This has been observed in some deployments on Linux.
Solution: rewrite omni_http'd fd.c to make more sense
The log message occurred because we were getting invalid fd (-1).
The original code made a number of (weird) things that somehow worked but weren't doing the right thing, particularly calculation of the message length. I am no longer sure why it was setting other fds to -1.
It's still far from perfect and #41 is still very important to ensure smooth operation.
> Problem: "socket error: Resource temporarily unavailable" log message

- .github/workflows/docker-publish.yml
Solution: propose an Action that makes builds and publishes to ghcr.io
> Problem: docker images need to be built manually

- .github/workflows/docker.yml
- Dockerfile
- cmake/FindPostgreSQL.cmake
The prepared packaged is only built for linux/amd64
Solution: use cross-platorm capabilities to build for ARM64
> Problem: using prepared Docker image on ARM CPUs

- .github/workflows/docker.yml
It takes too much space and the quota is rather limited (10GB)
Solution: cache the layers in S3
Also, since Docker builds are really slow, try using BuildJet
> Problem: docker layers caching in GHA

- .github/workflows/docker.yml
- Dockerfile
Solution: include respective language's runtimes in the image
> Problem: docker image fails to load plperl, pltcl and plpython

- .github/workflows/docker.yml
> Problem: Docker image caching doesn't work on arm64 runner

- extensions/omni_httpd/master_worker.c
Solution: check if creating a listening socket failed
What happened is that we didn't check whether creating listening socket was successful and tried to send `-1` to workers as a valid fd (which it isn't)
This will now produce a warning in the log. In the future, we should have a better alert/reporting system for improved visibility into the system and troubleshooting.
> Problem: sharing bad file descriptor in omni_httpd

- extensions/omni_httpd/master_worker.c
Symptom: pg_regress reporting that it can't shutdown postgres, exit code 256
Solution: ensure we're checking if shutdown is required in tight loops
We have a few loops where we're synchronizing with other workers. However, if the worker is being shut down, there's no point in this synchronization and it should just stop.
> Problem: sometimes CI can't shutdown omni_httpd

- Dockerfile
Noticed a major performance issue with running Omnigres from a container. It's about twice as slow!
Solution: move it from alpine/musl to debian/glibc
I've researched this issue and it turns out musl may have problematic components when it comes to performance in multithreaded/multiprocess environments. Not 100% sure this is the case, but I can see with my own eyes how changing to debian/glibs brought the performance back.
> Problem: container performance is about 50% of "as is"

- extensions/omni_httpd/http_worker.c
Solution: avoid incorrect disposal of listener contexts
The assertion failures are happening because some of the memory pointed to has been reclaimed.
Turns out, there is a bug in http_worker logic: it'll try to get new fds from the master_worker every time the event loop exits, without checking whether a worker reload flag has changed.
Since the currently used socket fd hasn't been closed, the socket received by http_worker has a different numeric value and the comparison in the logic leads to a decision to dispose of the listener context for the (wrongly assumed to be removed) fd.
However, there are still requests in flight, on a live socket and this rips out an allocation that is expected to be valid.
By ensuring that socket reload is done only when a reload is requested by …
> Problem: ocassional assert failures in libh2o

- extensions/omni_httpd/omni_httpd--0.1.sql
This is not a good practice to show.
Solution: extract such queries to stored procedures
> Problem: big queries in omni_httpd handler query

- cmake/PostgreSQLExtension.cmake
It has no syntax highlighting and at times, its output can be a bit clunky.
Solution: use pgcli when available
> Problem: psql is a bit barebones visually

- cmake/PostgreSQLExtension.cmake
- dynpgext/test/CMakeLists.txt
- extensions/omni_ext/test/CMakeLists.txt
- libpgaug/test/CMakeLists.txt
Solution: exclude them with `PRIVATE` flag
> Problem: test extensions get shipped in the container image

- extensions/omni_httpd/docs/headers.md
@ggaughan spotted them.
Solution: fix them
> Problem: typos in omni_httpd docs

- extensions/omni_types/expected/sum_type.out
- extensions/omni_types/sql/sum_type.sql
- extensions/omni_types/sum_type.c
Solution: ensure we test [de]TOASTing in more detail and fix packed toasted datums issue
> Problem: detoasting packed sum types may not work correctly

- extensions/omni_types/sum_type.c
Solution: switch to the "system" directories search path
> Problem: sum_types.c may pick up local headers for Postgres

- extensions/omni_types/sum_type.c
> Problem: unused code in sum_types

- pg_yregress/docs/usage.md
- pg_yregress/test.c
- pg_yregress/test.yml
Solution: handle notices and put them into `notices` if present
> Problem: not being able to test for notices in pg_yregress

- pg_yregress/CMakeLists.txt
- pg_yregress/docs/_install.md
- pg_yregress/docs/install.md
- pg_yregress/docs/usage.md
- pg_yregress/mkdocs.yml
Solution: provide instruction and an install target
We also have to exclude libfyaml from installation by using `EXCLUDE_FROM_ALL YES`.
> Problem: unclear how to install pg_yregress

- pg_yregress/pg_yregress.c
- pg_yregress/pg_yregress.h
- pg_yregress/test.c
It is not really necessary as document can be retrieved from the node.
Solution: remove it
> Problem: pg_yregress' ytest->doc field

- pg_yregress/pg_yregress.c
This can be confusing if it was made that way by mistake.
Solution: fail with an error if there's no valid instruction
Also, while at it, slightly improve reporting of errors in tests.
> Problem: tests without a valid instruction do nothing

- extensions/omni_seq/id.h
- extensions/omni_seq/test.yml
Solution: write a test and fix decoding
Decoding wrongly assumed the input was a varlena (was I asleep when I wrote this?) but it is actually StringInfo.
> Problem: how do we know omni_seq.id binary encoding works?

- pg_yregress/sighandler.c
Solution: ensure signal handler exits after cleanup
> Problem: pg_yregress doesn't terminate on Ctrl-C

- pg_yregress/docs/usage.md
- pg_yregress/test.c
- pg_yregress/test.yml
Add simplified form error reporting and support for error detail reporting
> Improvements to error reporting in pg_yregress

- cmake/FindPostgreSQL.cmake
Solution: update them to the recent releases
> Problem: outdated Postgres releases

- pg_yregress/pg_yregress.c
Solution: instead, make it exit
libfyaml does the diagnostic output for now
> Problrm: pg_yregress segfaults if file can't be opened

- extensions/omni_httpd/master_worker.c
This means that one will have to look into the logs to see what happened and adjust accordingly.
Solution: pick an unused port and record the effective port in effective_port like we do when using the wildcard (0) port.
Addresses #177
> Problem: omni_httpd will simply log an error if can't listen on a port

- pg_yregress/pg_yregress.c
- pg_yregress/test.c
This makes reading TAP outputs more difficult.
Solution: use TAP14's subtests
> Problem: pg_yregress bundles steps into top-level tests

- cmake/FindPostgreSQL.cmake
Solution: ensure we abort if there was a problem
> Problem: failing to build Postgres doesn't stop cmake

- extensions/omni_vfs/docs/reference.md
- extensions/omni_vfs/local_fs.c
- extensions/omni_vfs/omni_vfs--0.1.sql
- extensions/omni_vfs/tests/local_fs.yml
Solution: include `kind` column
> Problem: omni_vfs.file_info doesn't tell what kind of file it is

- extensions/omni_vfs/local_fs.c
This causes some additional and unnecessary overhead.
Solution: use prepared statements instead
> Problem: omni_vfs's local_fs reparses SQL queries

- .github/workflows/build.yml
Solution: try setting up homebrew separately
> Problem: homebrew failing on macOS

- extensions/omni_httpd/tests/handler_validity.yml
- extensions/omni_mimetypes/tests/test.yml
- extensions/omni_vfs/CMakeLists.txt
- extensions/omni_vfs/local_fs.c
- extensions/omni_vfs/pg_path.h
- extensions/omni_vfs/pg_path_v15.c
- pg_yregress/test.c
Solution: fix pg_yregress to set success to true
so that it fails if the expectation for the test is to fail.
> Problem: successful tests don't fail if success: false

- pg_yregress/test.c
When a sub-test fails in a group, it gets its nice expected/result YAML report to compare. However, its parent test will also fail (which is fine) but it'll print a much larger YAML report which obscures the smaller output and makes it harder to discover the actual failure.
Proposed solution: ensure parent tests don't print the expected/result YAML report on failure as sub-tests already do that.
It isn't perfect yet, I think, but seems to generally do the job. Area worth exploring is what happens if the `step` is also `commit: true` and it fails during the commit.
Fixes #222
> Problem: pg_yregress test group failure can be verbose

- extensions/omni_httpd/master_worker.c
If omni_httpd listener has a port specified (say, 8080) but it wasn't available to listen on, an effective port will be picked using operating system's facilities.
However, a subsequent update of a handler triggers omni_httpd to try listening 8080 again (which is not a bad idea to try and return it back to where it is intended to be), but if that fails again, a new port will be picked, which is suboptimal and (frankly) annoying.
Solution: try seeing if we're still listening on the effective port
If we do, use it. If we don't try to listen on it. If that doesn't work, let the operating system choose the port.
NB: there is currently no test for this behavior because it is predicated on the test to have a certain port listened on in any test environment (so that it returns `EADDRINUSE`) and …
> Problem: updating omni_httpd handler for a listener on an effective port

- pg_yregress/test.c
This makes it harder to read its code and is marginally slower.
Solution: extract a variable
> Problem: pg_yregress testing calls fy_node_document too much

- pg_yregress/pg_yregress.c
If you look into c80894560ad96abf1a84015977bf9c8ee02cc491, there was a fix of a bug where `negative` flag did not affect anything because the value of `commit` was used instead. This happened because `commit` was in scope there.
Solution: scope all these values so they don't leak
> Problem: uncertainty of long-winded pg_yregress processing

- extensions/omni_schema/omni_schema--0.1.sql
- extensions/omni_schema/tests/test.yml
Solution: write a test and fix a bug that caused re-running of migrations
> Problem: unclear if repeating migration will skip already migrated

- cmake/FindH2O.cmake
Solution: upgrade to a newer version
> Problem: outdated libh2o

- extensions/omni_httpc/tests/test.yml
- extensions/omni_httpd/omni_httpd.c
- extensions/omni_httpd/tests/http_response.yml
This is not a valid MIME type.
Solution: use the correct one (application/json)
> Problem: omni_httpd returns text/json for json types

- .github/workflows/build.yml
See https://github.com/douglascamata/setup-docker-macos-action/issues/20
Solution: use a new release of the Github Action
> Problem: macos builds fail on GitHub Actions

- cmake/PostgreSQLExtension.cmake
It is always random, and if we want to use it outside of this command, we have to grab from the connection. This is inconvenient.
Solution: allow specifying port with PGPORT environment variable
The command can look like this now:
```shell
PGPORT=5432 make psql_omni_...
```
> Problem: make psql_<COMPONENT_NAME> port selection

- .github/workflows/build.yml
- Dockerfile
- cmake/FindPostgreSQL.cmake
- docs/quick_start.md
- extensions/omni_ext/control_file.c
- extensions/omni_ext/init.c
- extensions/omni_httpd/omni_httpd--0.1.sql
- extensions/omni_httpd/tests/role.yml
- extensions/omni_seq/id.h
- extensions/omni_sql/CMakeLists.txt
- extensions/omni_sql/deparse_16.c
- extensions/omni_types/sum_type.c
- pg_yregress/test.yml
We really want 16 as it has a lot of significant improvements.
Solution: include it in the build
The most challenging piece here is updating omni_sql deparsing. It's not perfect yet and doesn't support all the changes but it should serve well for the initial goal of supporting Postgres 16.
Docker container temporarily uses our own build of postgres 16 container until Docker Hub gets 16.0 in.
> Problem: no support for Postgres 16

- cmake/FindH2O.cmake
Solution: update to a newever version to stay up to date
> Problem: libh2o is outdated

- cmake/FindH2O.cmake
(stands for Explicit Congestion Notification)
Solution: update to the latest version
> Problem: used version of h2o doesn't support H3 ECN

- cmake/FindH2O.cmake
There may have been fixes that are useful:
* https://github.com/h2o/h2o/commit/353976b68e70975b0aee5b7da72b264f3de60051
Solution: update it
> Problem: H2O is not up-to-date

- extensions/omni_txn/omni_txn.c
Solution: ensure we allocate copies of datum in transaction's context
Otherwise it is undefined behavior as to what we may be pointing to from the hash table.
> Problem: omni_txn variables may have unexpected values

- extensions/omni_ext/workers.c
When terminating Postgres normally, getting these messages:
```
FATAL:  terminating background worker "omni_ext worker (omni_httpd)" due to administrator command
FATAL:  terminating background worker "omni_ext master" due to administrator command
FATAL:  terminating background worker "omni_ext worker (postgres)" due to administrator command
LOG:  background worker "omni_ext worker (omni_httpd)" (PID 57270) exited with exit code 1
LOG:  background worker "omni_ext master" (PID 57215) exited with exit code 1
LOG:  background worker "omni_ext worker (postgres)" (PID 57217) exited with exit code 1
```
These look wrong: is something going on?
Solution: provide clean termination path in omni_ext instead
> Problem: noise during omni_ext shutdown

- extensions/omni_types/sum_type.c
Solution: ensure we use correct pointers
Honestly, this needs a bit more work in terms of documenting and refactoring. I've spent too much time tracing through this.
I am not sure why tests weren't failing before, but new pg_yregress tests were in #278
> Problem: omni_types layout is at times getting garbage data

- extensions/omni_containers/docs/intro.md
Solution: add examples demonstrating its usage
Closes #321
> Problem: omni_containers is undocumented

- extensions/omni_python/tests/omni_python_flask.yml
- languages/python/omni_http/src/omni_http/omni_httpd/__init__.py
- languages/python/omni_http/src/omni_http/omni_httpd/flask.py
Flask POST handlers are missing headers and body data.
https://discord.com/channels/1059495229243265096/1168330166842425374
> Problem: Flask POST methods not passing headers & body

- extensions/omni_python/docs/intro.md
Solution: Add examples demonstrating the usage of `omni_python`
Closes https://github.com/omnigres/omnigres/issues/320
> Problem: omni_python is undocumented

- extensions/omni_python/docs/intro.md
Solution: Fix the highlighted line range.
Test plan: Verified running mkdocs locally.
Screenshot:
> Problem: mkdocs highlighted line range is incorrect

- extensions/omni_schema/migrate/1_languages.sql
- extensions/omni_schema/migrate/2_aux_tools.sql
- extensions/omni_schema/migrate/4_load_from_fs.sql
- extensions/omni_schema/tests/fixture/omni_python/a_load_time_test.py
- extensions/omni_schema/tests/omni_python.yml
Solution: introduce tools/language ordering priority while sorting files by name for consistency
Closes #327
> Problem: omni_schema may load sources before dependencies are ready

- extensions/omni_python/tests/omni_python_flask.yml
- languages/python/omni_http/src/omni_http/omni_httpd/__init__.py
Solution: ensure we pass content type as CONTENT_TYPE in WSGI instead of HTTP_CONTENT_TYPE
https://peps.python.org/pep-3333/#environ-variables
> Problem: flask's request.content_type always returns None

- README.md
- extensions/omni_python/docs/intro.md
While in fact it is for multiple languages.
Solution: include a Python example
> Problem: README makes people think Omnigres is only for SQL

- extensions/omni_containers/docs/intro.md
- pg_yregress/docs/usage.md
> Problem: mistakes in `pg_yregress` and `omni_containers` docs

- .github/workflows/build.yml
> Problem: macOS GitHub Actions are extremely slow

- cmake/FindPostgreSQL.cmake
> Problem: building against older versions of Postgres

- README.md
This helped me get a local build on M2 latest MacOS with asdf managed python.
> Add build tips to readme

- pg_yregress/CHANGELOG.md
- pg_yregress/docs/usage.md
Solution: document and list it in the changelog
> Problem: pg_yregress' reset property is not documented

- extensions/omni_var/omni_var.c
Currently, transactional variables copy the values when a new sub-transaction is started, and the value is overwritten (or when we roll back to a savepoint (see uses of `memcpy`).
While it is not a significant concern, it is still less efficient than one would want. The size of `VariableValue` on a 64-bit platform could be 32 bytes.
Solution: always allocate `VariableValue`
This forces the variable value to always go through a pointer to get to the value. The initial allocation comes from the allocation done for `Variable`.
This way, we don't need to copy the variable value and simply change pointers.
> Problem: omni_var may be copying memory unnecessarily

- .github/workflows/build.yml
"Waiting for runner" and then nothing
Solution: try out WarpBuild
> Problem: buildjet CI runners get stuck sometimes

- .github/workflows/build.yml
- extensions/omni_aws/CMakeLists.txt
- extensions/omni_aws/tests/minio.yml
- extensions/omni_containers/migrate/2_docker_container_create.sql
- extensions/omni_containers/omni_containers.c
There's a lot of maintenance associated with it.
Solution: switch to GitHub runners
but move Docker to a separate CI Docker instance we maintain.
> Problem: running macOS for CI is painful

- extensions/omni_vfs/docs/reference.md
table_fs can only be discovered by reading the source code of omni_vfs, which is ultimately not great for DX.
Solution: document its usage
#433
> Problem: table_fs backend for omni_vfs discovery

- extensions/omni_httpd/omni_httpd.c
When doing so, the started version tends to get stuck after "Established listener on PORT" and not serve anything.
Solution: ensure we always determine the number of workers
This is now accomplished by looking at the string value. This is suboptimal as we're not able to observe changes to this the same way a GUC observation would, but it's still doable.
More context in #447.
> Problem: loading multiple versions of omni_httpd

- extensions/omni_ext/init.c
It happens when there are a lot of extensions being preloaded. However, we are not attempting to load all of them (which would, naturally, result in the exhaustion of worker slots if they register all of their background workers.)
Solution: drop the check
Pre-loading only means we've pre-allocated some resources to them but doesn't mean we'll ever register all the workers.
> Problem: omni_ext error of "Not enough workers allowed"

- cmake/FindH2O.cmake
Since the last update, it has received some updates to HTTP2 implementation, PicoSSL update and some other minor changes.
Solution: update to the lastest versiont
> Problem: h2o is a bit outdated

- cmake/Logtalk.cmake
> Problem: Logtalk 3.74.0 is slightly outdated now

- Dockerfile
- cmake/FindPostgreSQL.cmake
Solution: change defaults to the latest ones
> Problem: using slightly older versions of Postgres

- extensions/omni/hook_harness.c
Some of the code is not very clear on how single-shot xact callbacks operate. This is because they were a bit of a hack to begin with and we might want to improve this part of the extension soon.
But it's still difficult to understand how they operate
Solution: reorganize the code a bit, provide commentary
Also, got rid of unnecessary memory context switching as deletion from a list uses list's own memory context.
> Problem: clarity on single-shot xact callbacks

- cmake/FindH2O.cmake
There have been some useful and interesting fixes in h2o recently, for example:
* https://github.com/h2o/h2o/pull/3359
* https://github.com/h2o/h2o/pull/3360
* https://github.com/h2o/h2o/pull/3361
* https://github.com/h2o/h2o/pull/3356
Solution: update to the latest version
> Problem: h2o is slightly outdated

- cmake/Logtalk.cmake
- cmake/SWIprolog.cmake
There are some improvements that happened in latest versions.
Solution: upgrade to the latest versions
> Problem: slightly outdated SWI Prolog and Logtalk

- extensions/omni/omni.c
Solution: remove it, it was a debug printout
🤦
> Problem: unexplainable execution of syslog in omni

- extensions/omni_httpd/CHANGELOG.md
Changelog still contains TBD.
Solution: set the date
> Problem: missing release date for omni_httpd 0.1.2

- extensions/omni_sql/CHANGELOG.md
Solution: use the date of the actual release
> Problem: omni_sql 0.2.0 release date is not set

- extensions/omni_vfs/CHANGELOG.md
- extensions/omni_vfs/local_fs.c
- extensions/omni_vfs/tests/deleted.yml
- extensions/omni_vfs/tests/local_fs.yml
- versions.txt
Solution: bump up a version in anticipation of fixes
> Problem: omni_vfs has some bugs and issues (🚀 omni_vfs 0.1.1)

- extensions/omni/CHANGELOG.md
- extensions/omni/dshash_extras.h
- extensions/omni/omni.c
- extensions/omni/omni_common.h
Solution: use appropriate key/hash functions
> Problem: use of fragile code to ensure correctness of hashing

- extensions/omni/CHANGELOG.md
- extensions/omni_httpd/CHANGELOG.md
- extensions/omni_schema/CHANGELOG.md
- extensions/omni_sql/CHANGELOG.md
- extensions/omni_vfs/CHANGELOG.md
- pg_yregress/CHANGELOG.md
The year is wrong.
Solution: change 2023 to 2024
> Problem: incorrect dates in CHANGELOG files

- Dockerfile
> Problem: using outdated Postgres in the container

- cmake/FindPostgreSQL.cmake
Quite a bit of fixes!
https://www.postgresql.org/about/news/postgresql-164-158-1413-1316-1220-and-17-beta-3-released-2910/
Solution: upgrade to the latest ones
> Problem: slightly outdated minor versions of Postgres

- extensions/omni_web/CHANGELOG.md
- extensions/omni_web/src/cookies.sql
Solution: rewrite in PL/pgSQL and make it immutable
> Problem: omni_web.cookies is a bit slow

- extensions/omni_web/CHANGELOG.md
- extensions/omni_web/migrate/6_cookie_get.sql
- extensions/omni_web/src/cookie_get.sql
- extensions/omni_web/src/cookies.sql
- extensions/omni_web/tests/cookies.yml
- versions.txt
Solution: bump the version in anticipation of such changes
> Problem: omni_web needs some updates (🚀 omni_web 0.2.0)

- cmake/CPM.cmake
https://github.com/cpm-cmake/CPM.cmake
This may prevent us from having bug-fixes
Solution: upgrade to a newer one
While at it, switch to a full version, not the script that would download CPM. This still doesn't solve the issue of hermetic builds, but it's the first step towards it.
> Problem: using old CPM

- extensions/omni_httpd/CHANGELOG.md
Solution: start preparing for that
> Problem: omni_httpd needs some fixes (🚀 omni_httpd 0.2.1)

- extensions/omni_txn/CHANGELOG.md
- extensions/omni_txn/docs/retry.md
- extensions/omni_txn/migrate/4_retry_prepared_statements.sql
- extensions/omni_txn/omni_txn.c
- extensions/omni_txn/tests/retry_prepared_stmts.yml
This is not very efficient.
Solution: cache statement plans
> Problem: omni_txn.retry re-plans statements on every call

- extensions/omni_ledger/CMakeLists.txt
- extensions/omni_ledger/README.md
- extensions/omni_ledger/docs/account_categories.md
- extensions/omni_ledger/docs/basics.md
- extensions/omni_ledger/docs/ledger_core.md
- extensions/omni_ledger/docs/quickstart.md
- extensions/omni_ledger/migrate/1_core.sql
- extensions/omni_ledger/migrate/2_accounting.sql
- extensions/omni_ledger/mkdocs.yml
- extensions/omni_ledger/omni_ledger.c
- extensions/omni_ledger/src/account_categories_immutability.sql
- extensions/omni_ledger/src/deny_operation_on_immutable_table.sql
- extensions/omni_ledger/src/ensure_affected_accounts_accounting_balances.sql
- extensions/omni_ledger/src/ensure_affected_accounts_balance.sql
- extensions/omni_ledger/tests/accounting.yaml
- extensions/omni_ledger/tests/balance_slots.yaml
- extensions/omni_ledger/tests/core.yaml
- extensions/omni_ledger/tests/serializable.yaml
- versions.txt
At the core of many of these application there's a need for accounting for transfers of value. However, creating this is difficult because of subtle issues.
Solution: provide a ledgering extension (early preview)
> Problem: building fintech applications (🚀 omni_ledger 0.1.0)

- README.md
- extensions/omni_yaml/CMakeLists.txt
- extensions/omni_yaml/README.md
- extensions/omni_yaml/docs/yaml.md
- extensions/omni_yaml/migrate/1_yaml_functions.sql
- extensions/omni_yaml/mkdocs.yml
- extensions/omni_yaml/omni_yaml.c
- extensions/omni_yaml/tests/yaml.yaml
- versions.txt
There's plenty of YAML around but Postgres does not support it.
Solution: implement omni_yaml
This extension provides a simple way to convert YAML to and from JSON.
> Problem: not being able to use YAML (🚀 omni_yaml 0.1.0)

- extensions/omni_containers/CHANGELOG.md
- extensions/omni_containers/src/docker_container_create.sql
- extensions/omni_containers/tests/container.yml
- versions.txt
...if there's a custom tag.
Solution: ensure to handle custom tag
> Problem: docker_container_create does not pull an image

- extensions/omni_containers/CHANGELOG.md
- extensions/omni_containers/migrate/6_docker_container_exec.sql
- extensions/omni_containers/src/docker_container_exec.sql
- extensions/omni_containers/tests/container.yml
- versions.txt
Solution: enable executing in existing containers
This can be useful for container inspection
> Problem: limited Docker API coverage

- extensions/omni_containers/CHANGELOG.md
- extensions/omni_containers/docs/intro.md
- extensions/omni_containers/migrate/6_docker_container_exec.sql
- extensions/omni_containers/src/docker_container_create.sql
- extensions/omni_containers/src/docker_container_exec.sql
- extensions/omni_containers/tests/container.yml
- versions.txt
Solution: start keeping a changelog in anticipation
> Problem: omni_containers is overdue for some updates (🚀 omni_containers 0.2.0)

- cmake/FindPostgreSQL.cmake
There were some regressions and 17.2 is out now.
Solution: update to 17.2 and other majors accordingly
Dockerfile is not updated yet as the 17.2 image is not available yet.
> Problem: Postgres 17.1 is outdated

- extensions/omni/CHANGELOG.md
- extensions/omni/extension.c
- extensions/omni/hook_harness.c
- versions.txt
Solution: kickstart a bugfix release cycle
> Problem: omni has some bugs (🚀 omni 0.2.4)

- extensions/omni_vfs/CHANGELOG.md
- extensions/omni_vfs/CMakeLists.txt
- extensions/omni_vfs/local_fs.c
- extensions/omni_vfs/migrate/5_local_fs.sql
- extensions/omni_vfs/migrate/5_table_fs.sql
- extensions/omni_vfs/src/is_valid_fs.sql
- extensions/omni_vfs/src/write_table_fs.sql
- extensions/omni_vfs/tests/local_fs.yml
- extensions/omni_vfs/tests/table_fs.yml
In particular, there is no way to write to files.
Solution: design a simplistic write API
> Problem: omni_vfs API is limited

- extensions/omni_httpc/tests/redirect.yml
- extensions/omni_httpc/tests/test.yml
- extensions/omni_httpc/tests/timeout.yml
- extensions/omni_httpd/CHANGELOG.md
- extensions/omni_httpd/http_worker.c
- extensions/omni_httpd/tests/http.yml
Unless this IP comes from a third-party proxy, of course.
Solution: pass it through Omnigres-Connecting-IP header
> Problem: inability to retrieve HTTP request's source IP address

- extensions/omni_schema/CHANGELOG.md
- extensions/omni_schema/src/assemble_schema.sql
- extensions/omni_schema/tests/assemble_schema_syntax_error.yml
- extensions/omni_schema/tests/fixture/syntax_error/test.sql
Instead of providing an error in the assembly report, it fails by itself.
Solution: track the error in the report instead
> Problem: omni_schema.assemble_schema fails on syntax errors

- Dockerfile
- README.md
- docs/quick_start.md
- extensions/omni_python/docs/intro.md
What's the point?
Solution: install all pigsty images so that they are readily available.
> Problem: omnigres image not different from the slim one

- Dockerfile
- README.md
- docker/initdb-slim/999-ready.sql.templ
This port would rather be more useful for application's orbs.
Solution: move it to 8081
> Problem: exposing container's default service on 8080

- .github/workflows/docker.yml
- Dockerfile
- README.md
- docs/quick_start.md
- extensions/omni_python/docs/intro.md
This is making it harder for new users to start, especially if their connection isn't great.
Solution: rename slim to "no flavour" and "no flavour" to extra
> Problem: normal Omnigres image is too large

- Dockerfile
It throws away cached layers with installed packages because we copy from our build images first, and then install packages.
Solution: install packages first
This way we can reuse the cached layers.
> Problem: rebuilding container image

- CONTRIBUTING.md
- README.md
Solution: provide more details in CONTRIBUTING.md
This is an initial draft based on sparse notes.
> Problem: contribution process is unclear

- Dockerfile
Once you upgrade the image, previous versions of Omnigres extensions are gone. And if you had them provisioned in your database, well, good luck.
Solution: preserve previous extensions (effectively .control, .sql and .so files)
We do this by building an image off of the latest released image and copy pkglibdir and sharedir/extension into the new image, before installing Omnigres extensions.
This allows us to specify new default versions and override whatever files we'd like to override.
Since all releases go through a single point of CI in master, we'll release them sequentially. It may get a little dicey when builds fail and we don't retry them in time, but even then it's probably okay because it's still going to pick up the latest version. As long as we don't retry them out of order …
> Problem: upgrading Omnigres container images

- extensions/omni_schema/tests/meta_cast.yml
- extensions/omni_schema/tests/meta_extension.yml
- extensions/omni_schema/tests/meta_function.yml
- extensions/omni_schema/tests/meta_function_info_schema.yml
- extensions/omni_schema/tests/meta_function_parameter.yml
- extensions/omni_schema/tests/meta_relation.yml
- extensions/omni_schema/tests/meta_schema.yml
- extensions/omni_schema/tests/meta_sequence.yml
- extensions/omni_schema/tests/meta_table.yml
- extensions/omni_schema/tests/meta_table_privilege.yml
- extensions/omni_schema/tests/meta_table_rowsecurity.yml
- extensions/omni_schema/tests/meta_view.yml
- extensions/omni_schema/tests/meta_view_definition.yml
We understand all required invariants to build our diffing and migrations on top of it.
Solution: Increase test coverage
> Problem: We need to be able to refactor omni_schema views with confidence

- cmake/FindPostgreSQL.cmake
Latest Postgres fixed some bugs and CVEs
Solution: bump up the versions
> Problem: we're not having the latest Postgres

- extensions/omni_httpd/CHANGELOG.md
- extensions/omni_httpd/CMakeLists.txt
- extensions/omni_httpd/http_worker.c
- extensions/omni_httpd/migrate/11_routing.sql
- extensions/omni_httpd/omni_httpd.c
- extensions/omni_httpd/omni_httpd.h
- extensions/omni_httpd/src/regenerate_handler_trigger.sql
- extensions/omni_httpd/src/routes.sql
- extensions/omni_httpd/tests/null.yml
- extensions/omni_httpd/tests/portal_cleanup.yml
- extensions/omni_httpd/tests/router.yml
- extensions/omni_httpd/tests/worker_restart.yml
- extensions/omni_httpd/tests/xact.yml
- extensions/omni_httpd/tests/xact_iso.yml
- extensions/omni_httpd/urlpattern.cpp
- extensions/omni_httpd/urlpattern.h
- extensions/omni_rest/tests/cors.yml
- extensions/omni_rest/tests/get-horizontal-filtering.yml
- extensions/omni_rest/tests/get.yml
- extensions/omni_rest/tests/insert.yml
- extensions/omni_rest/tests/rpc.yml
- extensions/omni_rest/tests/update.yml
It's flexible but requires replacing a dispatch function. That is not a great experience and is not very introspectible.
Solution: introduce URLPattern-based matching
> Problem: omni_httpd request dispatch mechanism

- extensions/omni_schema/src/meta/catalog.sql
- extensions/omni_schema/tests/meta_trigger.yml
- extensions/omni_schema/tests/meta_trigger_arguments.yml
- extensions/omni_schema/tests/meta_trigger_callable.yml
- extensions/omni_schema/tests/meta_trigger_columns.yml
- extensions/omni_schema/tests/meta_trigger_deferrable.yml
- extensions/omni_schema/tests/meta_trigger_delete.yml
- extensions/omni_schema/tests/meta_trigger_enabled.yml
- extensions/omni_schema/tests/meta_trigger_initially_deferred.yml
- extensions/omni_schema/tests/meta_trigger_insert.yml
- extensions/omni_schema/tests/meta_trigger_level.yml
- extensions/omni_schema/tests/meta_trigger_truncate.yml
- extensions/omni_schema/tests/meta_trigger_update.yml
- extensions/omni_schema/tests/meta_trigger_when.yml
The view omni_schema.trigger is not in 6NF making a diff between rows harder.
Normalize it.
> Problem: The view omni_schema.trigger is not in 6NF

- extensions/omni_types/CHANGELOG.md
- extensions/omni_types/migrate/4_sum_type_provision_operators.sql
- extensions/omni_types/src/sum_type_provision_trigger.sql
- extensions/omni_types/sum_type.c
- extensions/omni_types/tests/sum_type.yml
Solution: introduce support for hash/btree indexing for sum types
> Problem: unable to index sum types

- cmake/FindPostgreSQL.cmake
Solution: bring the new versions as new defaults
I love the new weekly release schedule! :)
> Problem: current Postgres minors are outdated

- extensions/omni_python/CHANGELOG.md
- extensions/omni_python/migrate/7_packages.sql
- extensions/omni_python/src/install_requirements.py
- extensions/omni_python/src/installed_packages.py
- extensions/omni_python/tests/omni_python.yml
Solution: kick off the next release cycle
> Problem: omni_python is overdue for improvements (🚀 omni_python 0.2.0)

- extensions/omni_email/CHANGELOG.md
- extensions/omni_email/CMakeLists.txt
- extensions/omni_email/README.md
- extensions/omni_email/migrate/1_instantiate.sql
- extensions/omni_email/mkdocs.yml
- extensions/omni_email/src/instantiate.sql
- extensions/omni_email/src/instantiate_resend.sql
Solution: prototype a generalized email facility (omni_email)
> Problem: can't send emails to users (🚀 omni_email 0.1.0)

- extensions/omni_sqlite/CHANGELOG.md
- extensions/omni_sqlite/deps/cppgres.hpp
- extensions/omni_sqlite/omni_sqlite.cpp
That version of cppgres has severe deficiencies (for example, broken type checking in SPI)
Solution: update cppgres
> Problem: omni_sqlite uses older cppgres

- .github/workflows/build.yml
- .github/workflows/debug.yml
- .github/workflows/docker.yml
Ubuntu's PPA returns HTTP 504 Gateway Timeout quite often.
Solution: switch to a newer distro
to get the newer compiler we need
> Problem: intermittent failures in CI

- extensions/omni/CHANGELOG.md
- extensions/omni/extension.c
- extensions/omni/init.c
- extensions/omni/test/tests/late_ext.yml
- extensions/omni/workers.c
- versions.txt
Solution: kickstart a new development cycle
> Problem: omni extension needs fixes & improvements (🚀 omni 0.2.9)

- cmake/FindPostgreSQL.cmake
They are now slightly outdated
Solution: upgrade to 17.5, 16.9, 15.13 and 14.18
> Problem: default versions of Postgres releases

- extensions/omni_regex/docs/antora.yml
- extensions/omni_regex/docs/modules/ROOT/pages/index.adoc
Harder to use it in multi-module documentation projects.
Solution: start conversion to antora/asciidoc
> Problem: mkdocs are not enough

- cmake/FindPostgreSQL.cmake
Solution: bump the versions up
> Problem: last listed versions of Postgres are not last

- extensions/omni_kube/src/resource_table.sql
For example, the data may have been retrieved independently, or we're doing a
simulation. omni_kube's `refresh_RESOURCE` just calls the API.
Solution: switch to an aggregate instead
The old function is still available and wraps over the aggregate.
> Problem: impossible to refresh kube refresh tables off custom data 

- .github/workflows/cnpg.yml
- cnpg/Dockerfile
(CNPG standars for CloudNativePG)
Our current image is not based on their requirements.
Solution: build off their image
Also, instead of sharing the code with the container builder, let it clone it from the Git repo instead.
> Problem: deploying Omnigres in CNPG

- extensions/omni_worker/CHANGELOG.md
- extensions/omni_worker/deps/cppgres.hpp
- extensions/omni_worker/handlers.cpp
- extensions/omni_worker/omni_worker.cpp
- extensions/omni_worker/omni_worker.hpp
- extensions/omni_worker/src/instantiate.sql
- extensions/omni_worker/tests/sql.yml
- extensions/omni_worker/tests/sql_autostart.yml
- extensions/omni_worker/tests/timer.yml
- versions.txt
Solution: kickstart a new development cycle
> Problem: omni_worker needs further evolution (🚀  omni_worker 0.2.0)

- extensions/omni_kube/src/api.sql
- extensions/omni_kube/tests/noauth.yml
Solution: explicitly error out in this case
> Problem: omni_kube can fail silently if no credentials are available
