omnigres/omnigres

libgluepg_curl/libgluepg_curl.c

Solution: check for interrupts when receiving data
It's not perfect (what if there's no incoming data), but it's better than nothing at all.

Problem: fetching with CURL doesn't respond to query cancellation

---

cmake/FindPostgreSQL.cmake

Solution: ensure we listen on 0.0.0.0
This way psql's PGHOST is set to 0.0.0.0 and not *

Problem: tests started failing locally

---

cmake/FramaC.cmake
libgluepg_curl/CMakeLists.txt

It requires on knowledge of libpgext and it doesn't support targets with dependencies with includes unless those includes are listed explicitly.
Solution: scan through all direct dependencies to figure out all includes

Problem: hacky build configuration for Frama-c

---

cmake/FindCURL.cmake
cmake/FindYyjson.cmake
cmake/OpenSSL.cmake

This makes extension distribution more difficult.
Solution: make it statically linked against its dependencies
Not sure why `curl`'s CPM command didn't take OPTIONS well, but at
least this worked.

Problem: dependencies are dynamically linked

---

.github/workflows/build.yml
README.md
cmake/FindPostgreSQL.cmake

This makes it very difficult to work with independent builds.
Solution: deploy extensions within cmake build directory
The `deploy` and `deploy_NAME` targets are now gone.
This required a hack to make customizable PGSHAREDIR for testing purposes
but it seems to have work out alright.
Bumped up cache for .pg as it is now a patched version of Postgres.

Problem: polluting .pg with extensions

---

cmake/FindPostgreSQL.cmake

Solution: ensure pg_regress puts them into the right directory

Problem: <EXT>_update_results fails to apply outputs

---

.github/workflows/build.yml
.gitignore
cmake/FindPostgreSQL.cmake
docker/builder/Dockerfile

This is often requiring a trip to CI, which is not very ergonomic.
Solution: provide a simple builder Docker container
It seems to work, however, I am having difficulty making it work
with VirtioFS, when copying files, it seems to have a problem not
finding some files (spontaneously). Copying the source directory
away from a mounted volume helps. It also appears to work fine with
gRPC FUSE, but it is *extremely* slow.
That being said, [Colima](https://github.com/abiosoft/colima)-configured
context seems to work fine, a bit slower, but bearable.
This also changes the layout of the .pg directory, adding operating
system subdirectories to allow co-existence of Postgres builds for
different platforms.

Problem: testing on a Linux machine while on macOS

---

cmake/FindCURL.cmake
cmake/FindSTC.cmake

Solution: use CPM's `OPTIONS` parameter
I've previously failed to use it correctly by passing a single string,
it should have been multiple parameters.
While we're at it, set STC's version at something more appropriate than @91
guessed by CPM.

Problem: setting dependency options within the higher scope

---

cmake/FindPostgreSQL.cmake
cmake/OpenSSL.cmake
flake.lock
flake.nix

My Linux machine runs NixOS, and it's much easier to test Linux-specific bits on a real Linux machine as opposed to one in Docker. Especially when it comes to performance.
Solution: develop a Nix flake and adjust cmake to work with pkg-config

Problem: can't easily compile on NixOS

---

dynpgext/CMakeLists.txt
dynpgext/dynpgext.h
dynpgext/test/CMakeLists.txt
dynpgext/test/dynpgext_test--0.1.sql
dynpgext/test/dynpgext_test.c
dynpgext/test/expected/loader_present.out
dynpgext/test/sql/loader_present.sql
extensions/omni_ext/init.c

We can set a flag on `_Dynpgext_init` if the extension was loaded at a startup and use it to flag to `_PG_init` that there's no Dynpgext.
However, this won't work if the extension is loaded through the following sequence:
* CREATE EXTENSION
* SELECT omni_ext.load('extension_name') (or using other Dynpgext loader) This step may be a part of extension's SQL script.
At this point we can't tell if Dynpgext loader is present.
Solution: use a GUC variable to indicate Dynpgext loader presence
Open questions:
* How do we deal with multiple loaders present? Should this be possible?
* Can we expose loader function through Dynpgext interface so that `_PG_init` can call it so that we rely less on specific knowledge on how to load the extension.

Problem: Dynpgext extensions can be useless without a loader

---

.gitignore
Makefile

This is related to #36
Solution: add make test that will do it
Why did I name the directories `.b-VER`? It looks like I was running into path length restrictions in Postgres so I tried to cut down on these. It should be done more reliably.
But at least for now, run `make test` before you push so that you can potentially know the result sooner than CI telling you.

Problem: it's easy to forget to test against all Postgres versions

---

.github/workflows/build.yml
Makefile
README.md
cmake/FindH2O.cmake
cmake/FindMetalang.cmake
cmake/FindPostgreSQL.cmake
dynpgext/CMakeLists.txt
extensions/CMakeLists.txt
extensions/omni_httpd/CMakeLists.txt
extensions/omni_httpd/README.md
extensions/omni_httpd/expected/http.out
extensions/omni_httpd/fd.c
extensions/omni_httpd/fd.h
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/master_worker.c
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/omni_httpd.h
extensions/omni_httpd/sql/http.sql
libpgaug/libpgaug.h

These days it typically means running a web server or an application server of some kind that would connect to the database and interact with it to produce an output. This creates an overhead in operations and overall complexity.
Solution: make it possible to embed an HTTP server in Postgres
This is based on H2O, a "new generation HTTP server" with support for HTTP/1, HTTP/2 and (experimentally) HTTP/3. I have not yet enabled support for HTTP/3. It is also worth mentioning that even though HTTP/2 does work, it's not parallelizing multiple streams due to the current workers architecture. However, I do foresee this changing, just need to spend more time refining it.
Also, there's currently no support for SSL (coming) and building write AND read handlers may be problematic at the moment due …

Problem: exposing functionality of the database to the world

---

extensions/omni_httpd/expected/http.out
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/master_worker.c
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/sql/http.sql

Currently, if one wants to listen on different addresses at the same
time, responding with the same query, they'd have to copy the query
to every listener.
Solution: make listeners take an array of 'listenaddress'es
to serve multiple addresses with the same query

Problem: omni_httpd listening on different addresses

---

extensions/omni_httpd/http_worker.c

Solution: ensure it's cleaned up after an error, too

Problem: omni_httpd may leak constructed query

---

extensions/omni_httpd/expected/http.out
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/sql/http.sql

It seems to serve the same query over different listeners
Solution: ensure it actually checks the port
🤦

Problem: omni_httpd has problem starting multiple listeners

---

extensions/omni_httpd/CMakeLists.txt
extensions/omni_httpd/expected/role_name.out
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/sql/role_name.sql

This can be problematic when more complicated setups are used (outside of one user for everything, basically) and lead to security issues.
Solution: lower worker to a requested & validated user
`omni_httpd.listeners` table now takes a current user (and validates that it is current, therefore authorized) and http worker will set its role to the correct one when needed.

Problem: omni_httpd uses database's super user to run queries

---

cmake/FindPostgreSQL.cmake

Solution: ensure it is built with parallelization turned on
On my (fast) laptop, it took up to 140 seconds to do a build,
with this change, it's 32 seconds.

Problem: Postgres builds may be a bit slow

---

extensions/omni_httpd/http_worker.c

While there's no issue with the actual functionality (or at least it seems so), it makes reading code harder.
Solution: rename the shadowing variable

Problem: shadowing `nulls` variable

---

cmake/FindSTC.cmake

Solution: switch to recently released 4.1.1
It doesn't take advantaged of per-container custom allocators (https://github.com/tylov/STC/discussions/44#discussioncomment-4891925) but we can do this as a separate step to keep things simple.

Problem: using unreleased version of STC

---

cmake/PostgreSQLExtension.cmake
extensions/omni_ext/workers.c
extensions/omni_httpd/fd.c

Long-running transactions are problematic as they
can cause issues with database vacuuming.
Solution: ensure transactions are short-lived
but don't allocate a new XID.
This ensures we'll use `Assert` functionality from Postgres and fixes a bug from a misuse of it in omni_httpd while we're at it (otherwise it won't compile)

Problem: long-running transactions in omni_ext

---

extensions/omni_httpd/CMakeLists.txt
extensions/omni_httpd/http_worker.c
extensions/omni_sql/CMakeLists.txt
extensions/omni_sql/deparse.c
extensions/omni_sql/lib.c
extensions/omni_sql/omni_sql.c
extensions/omni_sql/omni_sql.h

omni_httpd doesn't publicly use any of omni_sql interface and therefore it is confusing why would it need to depend on omni_sql
Solution: extract libomnisql static library
and make omni_httpd use it directly instead of relying on an extension as it is indeed a bit more of an internal implementation detail, at least for now.
This also fixes a bug in deparsing where strings were duplicated with stdup instead of pstrdup (won't work with pfree and can lead to memory leaks otherwise)

Problem: not clear why omni_httpd requires omni_sql

---

extensions/omni_httpd/expected/http.out
extensions/omni_httpd/sql/http.sql

It's not great as we had to introduce priority and we're still executing more queries than necessary trying to find the "top priority" ones.
Solution: rewrite unions in cascading fashion
and use UNION ALL to avoid checking for duplicates.
This approach is a lot more verbose and harder to write correctly so a helper (aggregate?) function should perhaps be provided to build routing tables like this.

Problem: omni_httpd's example of union request "routing"

---

flake.lock
flake.nix

Format.cmake reports that clang-format and/or Python are not found.
Solution: include these in the Nix flake
Also, use the mainstream repo for nixpkgs as cmake 3.25.1 has been merged.

Problem: make fix-format doesn't work on NixOS

---

README.md

It's a barrier for entry.
Solution: document the availability of the pre-built image

Problem: having to pre-build Docker image

---

.github/workflows/gh-cleanup.yml
ci/github-actions-storage-cleanup

These count against the 10GB quota and they can be pretty big.
Solution: have a script to easily clean them up

Problem: merged PRs leave cache items in GitHub Actions

---

extensions/omni_httpd/master_worker.c
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/omni_httpd.h

It often works incorrectly as it is executed within the transaction, however, it communicates with master_worker and the worker is expected to pick up the configuration changes. If it will happen to process the configuration change *after* the commit, then all is good. Otherwise, the change won't be detected.
The trigger would notify the worker even if the transaction with the change will revert. It's probably not a big deal (since no changes will be visible to the worker) but it triggers the worker to go into the reload mode unnecessarily.
Solution: switch to using NOTIFY/LISTEN mechanism
This is a better mechanism as it will only be executed when the transaction succeeds and will not be duplicated (which may be important when the configuration will grow beyond just one table.)

Problem: reload_configuration trigger fragility

---

extensions/omni_httpd/master_worker.c
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/omni_httpd.h

After we've started using Notify/Listen mechanism, the use-case for the dedicated shared latch is seemingly gone. What's even worse, is that it is relatively fragile. If the worker crashes, the latch doesn't get disowned and therefore, on a subsequent restart, it can't be re-owned again. This makes code really fragile.
Solution: remove the latch altogether

Problem: omni_httpd's master_worker latch

---

extensions/omni_httpd/expected/http.out
extensions/omni_httpd/sql/http.sql

This test  sometimes returns 56 exitcode instead of 7 (connection refused):
```
\! curl --silent -w '%{exitcode}\n' http://localhost:9000/test?q=1
```
Solution: test for request failure instead of specific code
Most likely, the flakiness is introduced by how (soon) the socket is closed during the asynchronous omni_httpd configuration update.

Problem: omni_httpd's test is flaky

---

.github/workflows/docker.yml

They do have a point.
Solution: try and see if buildx will work without keys in a PR

Problem: AWS is really unhappy about public r/o key exposure

---

extensions/omni_httpd/expected/http.out
extensions/omni_httpd/expected/role_name.out
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/master_worker.c
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/sql/http.sql
extensions/omni_httpd/sql/role_name.sql

It conflates listeners and queries to execute and will not work well when HTTPS support will be added.
Solution: normalize omni_httpd configuration
Now there are three tables (`listeners`,`sqlets` and `listeners_sqlets`) that serve the same purpose. It gets a little noisier to work with these but this shouldn't happen often.

Problem: omni_httpd.listeners table is not great

---

cmake/PostgreSQLExtension.cmake

When I change script file in an extension, and build the extension, the new version of the script file does not get picked up.
Solution: ensure it is symbolically linked
instead of being a hard link
I've noticed that previously, only rerunning `cmake` was updating the file.
The original intention was to have this file symlinked, but I did not understand CREATE_LINK's default behaviour.

Problem: changes in script files don't make it

---

extensions/omni_httpd/CMakeLists.txt
extensions/omni_httpd/cascading_query.c
extensions/omni_httpd/docs/intro.md
extensions/omni_httpd/expected/cascading_query.out
extensions/omni_httpd/expected/http.out
extensions/omni_httpd/mkdocs.yml
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/sql/cascading_query.sql
extensions/omni_httpd/sql/http.sql
extensions/omni_sql/lib.c
extensions/omni_sql/omni_sql.h
mkdocs.base.yml

Writing something like this:
```sql
WITH test AS (SELECT omni_httpd.http_response(body := 'test') FROM request
WHEREE request.path = '/test'),
ping AS (SELECT omni_httpd.http_response(body := 'pong') FROM request WHERE request.path = '/ping')
SELECT * FROM test
UNION SELECT * FROM ping WHERE NOT EXISTS (SELECT FROM test)
```
is tedious and error-prone, especially when it comes to the union part.
Solution: make an aggregate function that simplifies this

Problem: writing cascading routing queries by hand

---

extensions/omni_httpd/CMakeLists.txt
extensions/omni_httpd/cascading_query.c
extensions/omni_httpd/docs/intro.md
extensions/omni_httpd/expected/handler_validity.out
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/sql/handler_validity.sql
extensions/omni_sql/CMakeLists.txt
extensions/omni_sql/expected/validity.out
extensions/omni_sql/lib.c
extensions/omni_sql/omni_sql--0.1.sql
extensions/omni_sql/omni_sql.c
extensions/omni_sql/omni_sql.h
extensions/omni_sql/sql/validity.sql

If given queries can't be executed, they will lead to an error and effectively HTTP 500. This is not great because (for example), a simple typo won't be noticed until it results in a runtime error.
Solution: enforce query validity at the transaction boundary
We are using a deferred constraint trigger to verify that at the transaction boundary, the query has to be correct.
This is not bulletproof as the query may become invalid at a later time (say, when a relation used in it is removed), but at least it is better than not doing any checks.
This change also brings query validation primitve to omni_sql (to be improved at a later point)

Problem: omni_httpd.handlers queries can lead to runtime errors

---

.github/workflows/build.yml

It can take a while.
Solution: print the artifacts upon failure

Problem: waiting for CI artifacts on build failures

---

extensions/omni_httpd/http_worker.c
extensions/omni_httpd/master_worker.c
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/omni_httpd.h

Solution: ensure master_worker wait for all http_workers before it commits the configuration reload record.
This is done with an atomic counting semaphore.

Problem: spontaneously failing omni_httpd tests

---

extensions/omni_httpd/master_worker.c

This is because of `pg_atomic_compare_exchange_u32` does:
```
The current value of *ptr will always be stored in *expected.
```
This means the semaphore we established still won't work correctly. This is what coding late at night some time leads to.
Solution: ensure resetting `expected` on every attempt to exchange

Problem: omni_http config reload may still not wait for http workers

---

extensions/omni_httpd/http_worker.c
extensions/omni_httpd/master_worker.c

During startup of the workers, we don't know how many of HTTP workers have started their loops by the time master worker's loop may be already ready for a configuration reload and signalling these workers to go into reload.
Solution: ensure we wait until HTTP workers enter their loops

Problem:  omni_httpd startup race condition

---

extensions/omni_httpd/cascading_query.c
extensions/omni_httpd/expected/cascading_query.out

When moving CTEs to the top, `cascading_query` will leave queries looking like this:
```
WITH SELECT ...
```
which is not going to parse.
Solution: ensure nulling `withClause`, not the list of CTEs

Problem: omni_httpd.cascading_query may generate invalid syntax

---

.github/workflows/build.yml
extensions/omni_ext/control_file.c

Supplying an absolute pathname there is often impractical and leads to errors like this:
```
omni_ext_test[6239] ERROR:  could not access file "/Users/yrashk/Projects/omnigres/omnigres/build/extensions/omni_ext/test/omni_ext_test_no_preloa":
No such file or director
```
Solution: try to symlink long paths to $TMPDIR
and see if they fit.

Problem: BGW_MAXLEN is too short

---

extensions/omni_httpd/http_worker.c
extensions/omni_httpd/http_worker.h

Instead of showing test_user it shows the name of the OS user (default username used for the database)
Solution: use role ID instead of name
It's simpler (as long as user ID doesn't change)

Problem: ocassionally role_name test fails

---

extensions/omni_httpd/expected/http.out
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/http_worker.h
extensions/omni_httpd/sql/http.sql

How do we know what's supplied can be converted to `omni_httpd.http_request` type?
Solution: write a test that tries to do this
The tests showed that `request` CTE was not in fact compatible with the type. This change fixes this.

Problem: omni_httpd's `request` CTE may not be `http_request`

---

extensions/omni_httpd/docs/intro.md
extensions/omni_httpd/expected/cascading_query.out
extensions/omni_httpd/expected/http.out
extensions/omni_httpd/sql/cascading_query.sql
extensions/omni_httpd/sql/http.sql

As used right now, the aggregate is not guaranteed to produce the query in the intended order.
From Postgres documentation:
```
Ordinarily, the input rows are fed to the aggregate function in an
unspecified order. In many cases this does not matter; for example, min
produces the same result no matter what order it receives the inputs in.
However, some aggregate functions (such as array_agg and string_agg)
produce results that depend on the ordering of the input rows. When
using such an aggregate, the optional order_by_clause can be used to
specify the desired ordering.
```
Solution: use `ORDER BY` clause inside the aggregator.

Problem: cascading_query() aggregate use and ordering

---

extensions/omni_httpd/CMakeLists.txt
extensions/omni_httpd/expected/http_response.out
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/sql/http_response.sql

When given NULL parameters, it will.
Solution: check for NULL and provide defaults where appropriate
While at it, fixed a bunch of issues pertaining to http headers array manipulation.

Problem: http_response function may crash

---

extensions/omni_web/expected/smoketest.out
extensions/omni_web/omni_web--0.1.sql
extensions/omni_web/sql/smoketest.sql

However, omni_httpd.http_request.body is a bytea
Solution: make it take bytea, too

Problem: parse_query_string takes text only

---

cmake/PostgreSQLExtension.cmake

Sometimes, a lot of tests change at once (code reformatting is one example) and updating expected results one component at a time (with `make <COMPONENT>_update_results`) can be a frustrating experience.
Solution: add `update_test_results` target to update them all

Problem: updating test results of multiple components

---

docker/initdb/001-settings.sql
docker/initdb/003-default-extensions.sql
docker/initdb/003-httpd.sql

However, there's also useful functionality in omni_web, and without it, examples from the documentation may not work.
Solution: include omni_web by default as well.

Problem: container image contains omni_httpd only

---

extensions/omni_httpd/CMakeLists.txt
extensions/omni_httpd/docs/headers.md
extensions/omni_httpd/expected/headers.out
extensions/omni_httpd/mkdocs.yml
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/sql/headers.sql

This requires processing an array and ensuring case is correct. However, this is such a common piece of functionality that it should be simpler.
Solution: add `http_header_get` and `http_header_get_all` functions

Problem: accessing HTTP headers

---

extensions/omni_httpd/expected/role_name.out
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/sql/role_name.sql

It must be current_user and that's it. While one can change roles to set it, it is rather incovenient.
Solution: allow changing to roles that are accessible to the current_user

Problem: can't lower omni_httpd handler role

---

README.md
extensions/omni_web/expected/params.out
extensions/omni_web/omni_web--0.1.sql
extensions/omni_web/sql/params.sql

It requires a lot of typing:
```
omni_web.param_get(omni_web.parse_query_string(...), param)
```
Solution: accept text & bytea as params and parse them on the fly

Problem: using omni_web.param_get family

---

extensions/omni_httpd/expected/port_selector.out
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/master_worker.c
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/omni_httpd.h
extensions/omni_httpd/sql/port_selector.sql

When a port is specified as 0, omni_httpd will update it with the actual port. However, this means that on the restart, it'll keep using that port that was selected once.
The intention of using zero is to say, "pick one." And restarts should honour this.
Proposed solution: add effective_port column
This way omni_httpd can use it always update to set the selected port.
While at it, changed relevant SQL code in C files to be lowercase to match the style elsewhere.
Closes #111

Problem: updating omni_httpd.listeners port

---

extensions/omni_httpd/omni_httpd.c

While it can be changed, it is not clear why this would be the best default for any system. Frankly, I think this was set this way because my current computer has 10 cores.
Solution: use _SC_NPROCESSORS_ONLN where available
According to manpages, Linux, macOS and FreeBSD have it.

Problem: hard-coded default of 10 http workers

---

.github/workflows/build.yml
docs/requirements.txt
extensions/omni_httpd/CMakeLists.txt
extensions/omni_httpd/docs/architecture.md
extensions/omni_httpd/event_loop.c
extensions/omni_httpd/event_loop.h
extensions/omni_httpd/expected/http2_reproxy.out
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/http_worker.h
extensions/omni_httpd/mkdocs.yml
extensions/omni_httpd/sql/http2_reproxy.sql
mkdocs.base.yml

Every HTTP worker is currently going busy when getting a new connection and a request.
This works (and having more than one worker ensures there are more workers to accept new connections), however, it negatively impacts HTTP/2 multiplexing. Once the worker is processing the request, it will not be processing other requests.
Solution: run HTTP processing event loop in a separate thread and use the primary thread for maintenance operations and executing Postgres handlers.
In addition, if there are requests in flight (defined as Postgres executing something), and the protocol is 2 or above, proxy the request back. It's not perfect as at times it is faster to wait than reprocess the query elsewhere, but we'd need a more sophisticated mechanism to handle this. Or maybe more tuning knobs. …

Problem: omni_httpd workers are blocking

---

cmake/PostgreSQLExtension.cmake

The .so files were no longer shipped, however.
Solution: ensure we don't put them together if extension is private

Problem: private extension control files are still shipped

---

.github/workflows/docker.yml
Dockerfile
docker/initdb-slim/001-settings.sql
docker/initdb-slim/002-restart.sh
docker/initdb-slim/003-default-extensions.sql
docker/initdb/001-settings.sql
docker/initdb/004-plrust-settings.sql
docker/initdb/005-restart.sh
docs/quick_start.md

pl/pgsql is useful but not performant.
Solution: include freshly released plrust
The Dockerfile for this isn't perfect (particularly, it won't handle
past versions of releases well because cargo pgx init gets the latest
ones, and we rely on PG, which might not match)

Problem: limited programming language options

---

cmake/PostgreSQLExtension.cmake
docker/initdb-slim/001-settings.sql
docker/initdb/001-settings.sql
extensions/omni_ext/CMakeLists.txt

Looks a bit awkward. The thing is, omni_ext is not upgradable in runtime and therefore having a versioned name will likely not be beneficial in any way.
Solution: introduce UNVERSIONED_SO property
that makes extension shared object unversioned.

Problem: naming omni_ext extension omni_ext--0.1

---

.github/workflows/docker.yml

Solution: make them use a bucket in the EU
I've replicated the original bucket to this one in the EU.

Problem: BuildJet runners are slow downloading big layers

---

Dockerfile

This limits its usability when it comes to writing some logic.
Solution: include all standard PLs and pljava
The non-slim image gets all of this, too, of course.

Problem: omnigres slim image contains no additional PLs

---

extensions/CMakeLists.txt
extensions/omni_types/CMakeLists.txt
extensions/omni_types/docs/sum_types.md
extensions/omni_types/expected/sum_type.out
extensions/omni_types/mkdocs.yml
extensions/omni_types/omni_types--0.1.sql
extensions/omni_types/sql/sum_type.sql
extensions/omni_types/sum_type.c

Sometimes under the wraps of one type we need to return distinctly different values. For example, if omni_httpd wants to handle different type "reactions" to an HTTP request (respond, upgrade, etc.).
Solution: implement sum types in omni_types extension
This is also known as enum or union.

Problem: returning distinctly different values of a type

---

extensions/omni_types/expected/sum_type.out
extensions/omni_types/sql/sum_type.sql
extensions/omni_types/sum_type.c

They are declared as PLAIN and can't be TOASTed
Solution: declare variable-sized sum types EXTENDED and ensure to use detoasting when retrieving them.

Problem: sum types can't be toasted

---

extensions/omni_types/expected/sum_type.out
extensions/omni_types/sql/sum_type.sql
extensions/omni_types/sum_type.c

It may look like this:
```
A result of type anyarray requires at least one input of type
anyelement, anyarray, anynonarray, anyenum, anyrange, or anymultirange.
```
Solution: handle it explictly with a clear error

Problem: error clarity when defining sum type with a pseudotype

---

extensions/omni_types/expected/sum_type.out
extensions/omni_types/omni_types--0.1.sql
extensions/omni_types/sql/sum_type.sql
extensions/omni_types/sum_type.c

It'll dump OIDs for sum types
Solution: make it dump type names instead by using `regtype`

Problem: pg_dump won't export omni_types.sum_types correctly

---

extensions/omni_types/expected/sum_type.out
extensions/omni_types/sql/sum_type.sql
extensions/omni_types/sum_type.c

This may reduce communication efficiency.
Solution: enable binary I/O if all variants have it
The encoding is 32-bit network-order discriminant followed by the encoding of the variant.

Problem: no binary I/O for sum types

---

extensions/omni_types/docs/sum_types.md
extensions/omni_types/expected/sum_type.out
extensions/omni_types/omni_types--0.1.sql
extensions/omni_types/sql/sum_type.sql
extensions/omni_types/sum_type.c

This means that if we want to add a variant, we have to create a new type and migrate to it.
Solution: allow amending sum types
For variably sized sum types, adding any new variants is permitted. For fixed sized ones, only variants of the same size or smaller are accepted. The reason for this is that if it was larger, then we'd have to change the size of the type and Postgres would attempt to use this size to read existing values which is clearly wrong.

Problem: sum types can't be changed

---

extensions/omni_httpd/event_loop.c
extensions/omni_httpd/event_loop.h
extensions/omni_httpd/http_worker.c

Solution: ensure we actually allocate them on h2o pool
The way headers were passed, they were simply pointers to Postgres-allocated memory. It worked before when we sent response inline, in one process. But we now send them in a different I/O thread and that was causing problems.
I've made sending body follow the same pattern for consistency.
It looks like we're now able to get higher throughput with this. Not sure how to explain this, though. In my limited benchmarking, up to two times faster than before!
I wonder if we can get rid of extra allocations/copies here in the future. For example, by de-parenting the memory context and sweeping leaked contexts at a later time?

Problem: some responses have garbage in headers

---

extensions/omni_httpd/event_loop.c
extensions/omni_httpd/event_loop.h
extensions/omni_httpd/http_worker.c

Given sufficient amount of requests, the CPU starts spinning and no new requests are served, at least not for a while.
Solution: ensure we don't let evloop poll it again
By simply returning from on_accept, evloop schedules it again to read,
in perpetuity. We disable accepting until the number of requests in flight
comes down to zero.
Importantly, we should decrement the number on the right thread
(event_loop)

Problem: omni_httpd seems to hang

---

extensions/omni_httpd/CMakeLists.txt
extensions/omni_httpd/docs/reverse_proxy.md
extensions/omni_httpd/event_loop.c
extensions/omni_httpd/event_loop.h
extensions/omni_httpd/expected/http.out
extensions/omni_httpd/expected/http_response.out
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/http_worker.h
extensions/omni_httpd/mkdocs.yml
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/omni_httpd.h
extensions/omni_httpd/sql/http.sql
extensions/omni_types/CMakeLists.txt
extensions/omni_types/expected/sum_type.out
extensions/omni_types/expected/unit.out
extensions/omni_types/omni_types--0.1.sql
extensions/omni_types/omni_types.c
extensions/omni_types/sql/sum_type.sql
extensions/omni_types/sql/unit.sql
extensions/omni_types/sum_type.c
extensions/omni_types/sum_type.h
extensions/omni_types/unit.c
mkdocs.base.yml

There's currently no way to do anything else like proxying a connection,
upgrading to WebSockets, etc.
Solution: use omni_types to make http_outcome sum type
There are now few outcomes: http_response, abort and http_proxy.
This also adds `omni_types.unit` to be used as a unit variant.

Problem: HTTP handlers can only respond

---

extensions/omni_httpd/docs/security.md
extensions/omni_httpd/expected/role_name.out
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/http_worker.h
extensions/omni_httpd/mkdocs.yml
extensions/omni_httpd/sql/role_name.sql

Solution: write a test case and fix it
Turns out, they can by setting role to NONE or resetting the role.
Fix it by using SECURITY_LOCAL_USERID_CHANGE unless the requested role is a supervisor.

Problem: unsure if omni_httpd handlers can escalate privileges

---

pg_yregress/CMakeLists.txt
pg_yregress/docs/usage.md
pg_yregress/pg_yregress.h
pg_yregress/test.c
pg_yregress/test.yml
pg_yregress/yaml.c

This is problematic as both pg_regress text-based tests and current pg_yregress tests are not a great fit for these.
Solution: provide `binary` property that regulates the format

Problem: testing binary encoding of Postgres types

---

pg_yregress/instance.c
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h

This can happen in some abnormal termination scenarios.
Solution: link instances into the same process group as pg_yregress

Problem: pg_yregress may not always terminate postgres

---

pg_yregress/instance.c
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h
pg_yregress/test.yml

If one is to be used often, it'll have to be specified in each test.
Solution: make it possible to declare an instance a default one

Problem: specifying multiple pg_yregress instances

---

pg_yregress/docs/usage.md
pg_yregress/instance.c
pg_yregress/pg_yregress.h
pg_yregress/test.yml

Sometimes this may be necessary, like changing some system parameters with SQL.
Solution: allow use of `restart` key in instance configuration

Problem: impossible to restart tested instance

---

pg_yregress/docs/usage.md
pg_yregress/instance.c
pg_yregress/test.yml

Sometimes this is warranted (we want to execute some SQL before modifying the config), but oftentimes it is not.
Solution: allow passing configuration through `config` property

Problem: configuring pg_yregress instances requires a restart

---

pg_yregress/docs/usage.md
pg_yregress/pg_yregress.c
pg_yregress/test.yml

Sometimes it is useful to do so if not everything can be hard-coded.
Solution: pass environment variables through `env` property

Problem: unable to pass configuration to the test suite

---

pg_yregress/docs/usage.md
pg_yregress/instance.c
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h
pg_yregress/test.c
pg_yregress/test.yml

One needs to write
```yaml
- query: ...
```
This is not the case in `init:`
Solution: allow simple string values for queries
Those will be checked for success.
This has paved the way to unifying `init` and test execution and error reporting methods.

Problem: some simple tests in pg_yregress are verbose

---

pg_yregress/docs/usage.md
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h
pg_yregress/test.c

They require diffing YAML (manually or automated) and sometimes this is just an extra step.
Solution: provide TAP output for TAP consumers
This is useful for reporting test execution and can be used to easily identify which tests failed.

Problem: reading pg_yregress reports

---

pg_yregress/docs/usage.md
pg_yregress/instance.c
pg_yregress/pg_yregress.h
pg_yregress/test.c
pg_yregress/test.yml

Testing JSON and JSONB parameters and results requires writing JSON as string, which is annoying and error-prone.
Solution: detect the use of JSON and use YAML to represent it

Problem: dealing with JSON in pg_yregress

---

pg_yregress/docs/usage.md
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h
pg_yregress/test.c
pg_yregress/test.yml

For example, when transaction is committed, constraints can be checked at the transaction boundary.
Solution: allow specifying whether test should be committed (false by default)

Problem: impossible to test side-effects of transactions

---

pg_yregress/test.c
pg_yregress/test.yml

This is happening with its own test suite.
Solution: ensure errored transactions are restarted and pg_yregress counts skipped tests.
If steps are skipped because the sequence of steps has failed, count them as skipped.
However, if the transaction has failed expectably (an expected error), roll it back and start it anew so that remaining tests can be used. This helped finding a test that should have failed but didn't.

Problem: pg_yregress under-reports tests

---

pg_yregress/docs/usage.md
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h
pg_yregress/test.c
pg_yregress/test.yml

Developing tests is complicated. Sometimes tests fail for no apparent reason (but we want to write them down and have our reports indicate them) or being worked on.
Solution: introduce `skip` and `todo` directives with TAP support

Problem: different states of tests in pg_yregress

---

extensions/omni_httpd/http_worker.c

Before acc3973d34b012d7ba988fa355344a69a70f1707, there was an `append` attribute in headers, but it is gone now. However, it was still being retrieved. Valgrind pointed that out.
Solution: make it always set headers
I am not sure why `append` was removed. Unfortunately, I didn't record this decision in the aforementioned change.

Problem: trying to get non-existent header attribute

---

extensions/omni_httpd/http_worker.c

Currently, it can lead to double free as it links the socket into the linked list by registering stoppage of reading and then registering a request to dispose it.
Solution: don't register the stoppage of reading
Also, while at it, properly cleanup the export.

Problem: omni_httpd socket closing procedure

---

extensions/omni_httpd/event_loop.c
extensions/omni_httpd/event_loop.h
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/master_worker.c
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/tests/role.yml

At times, HTTP connections are refused
Minor improvement: ensure we wait for the initial omni_httpd load
From https://github.com/omnigres/omnigres/issues/186#issuecomment-1570508233:
```
I think this is what is happening:
When omni_httpd is started with no_init (no default listener), upon
startup, the master worker reads the configuration, finds no listeners,
and proceeds to insert a record into configuration_reloads, which
indicates that a reload has happened. And in a sense, it has, however,
it is a "nil" configuration. We could make it conditional, saying
there won't be a reload notification if there are no listeners (or the
listener configuration hasn't changed). However, this is
problematic:
We don't check the handlers and if their configuration changed (this is
currently the …
```

Problem: omni_httpd's role.yml test is flaky

---

pg_yregress/pg_yregress.c

In rare cases, when, for example, being instrumented, pg_config will print instrumentation information on stderr and pg_yregress will consume this information, too.
Solution: send stderr to /dev/null to avoid reading it

Problem: pg_yregress invocation of pg_config may fail

---

cmake/PostgreSQLExtension.cmake
extensions/omni_vfs/docs/reference.md
extensions/omni_vfs/local_fs.c
extensions/omni_vfs/omni_vfs--0.1.sql
extensions/omni_vfs/tests/local_fs.yml

Currently, this requires one to write out a recursive query. At least that's the idea.
It's going to be very useful for facilitating smoother development environment experience (interacting with the working directory)
Solution: add `list_recursively()` function to make it reusable
While at it, document things.
Few fixes were made as well:
* `realpath()` was replaced with `make_absolute_path()` from Postgres to avoid symlink resolution.
* `chunk_size` is now `int` instead of `bigint` because there is a 1GB limit anyway (noticed during documenting)
* `omni_vfs.list()` got a new parameter of `fail_unpermitted`, primarily for the benefit of `list_recursively()` as it'd error out trying to list. It will make it a warning instead.

Problem: listing files recursively in omni_vfs

---

extensions/omni_vfs/local_fs.c

It doesn't actually happen and manifests in other pieces of code getting garbage instead of proper data.
Solution: ensure we capture the result of `SPI_transferDatum`
Also, remove the unnecessary manipulations of the memory context as these are done by `SPI_transferDatum`. They are only necessary if we use `transferDatum`.

Problem: omni_vfs.local_fs() transfer of the result

---

extensions/omni_vfs/local_fs.c

It's harmless, but there's no reason for it.
Solution: remove it

Problem: unused saved MemoryContext in omni_vfs

---

.github/workflows/build.yml
cmake/FindPostgreSQL.cmake
cmake/FramaC.cmake
cmake/PostgreSQLExtension.cmake

This is problematic when we want to be able to build exensions against Postgres installed using system-wide package manager or any other method.
For example, this would be useful for building extensions for specific Linux distros.
Solution: allow this by taking `PG_CONFIG` variable to specify `pg_config`
The command would now look like:
```shell
cmake -DPG_CONFIG=/path/to/pg_config # for example, $(which pg_config)
```
We won't be able to run psql or test targets yet because of how we ship extensions using patched Postgres. Same applies to Frama-C tests. But I think that this is okay for the time being. If you want to develop and test, self-managed Postgres builds are okay. It would be great to improve this in the future, but not a huge priority at the moment.

Problem: our build process only uses self-managed Postgres builds

---

extensions/omni_httpd/tests/role.yml
extensions/omni_mimetypes/tests/test.yml
extensions/omni_schema/tests/test.yml
extensions/omni_seq/tests/test.yml
extensions/omni_vfs/tests/local_fs.yml
extensions/omni_web/tests/query_string.yml
pg_yregress/CMakeLists.txt
pg_yregress/docs/usage.md
pg_yregress/instance.c
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h
pg_yregress/test.c
pg_yregress/test.yml

That is, it will put `t` or `f` into results. However, this is inconsistent with the rest of the YAML file where booleans are denoted standard YAML scalars for booleans.
Solution: use `true` and `false` values for booleans
This solution is not yet perfect because the comparison will not work correctly for different variations of the boolean scalars in YAML. Fixing this will require implementing custom comparator and this hinges on being able to (ideally) reuse the standard comparison algorithms with boolean comparison on top of it. I've previously sent a PR: https://github.com/pantoniou/libfyaml/pull/85 but it wasn't merged yet.

Problem: pg_yregress uses Postgres notation for booleans

---

extensions/omni_httpd/tests/http.yml
extensions/omni_httpd/tests/http2_reproxy.yml
extensions/omni_httpd/tests/role.yml

The server is not ready to respond for the first request.
Solution: ensure we wait for the initial start of the server

Problem: omni_httpd tests fail sometimes

---

.github/workflows/build.yml

The error looks like this:
```
brew update
brew install openssl@3.0 coreutils
shell: /bin/bash -e {0}
error: Could not read ffac597fdb6ce8236b5e2da77ab6fbae3d9d9cb7
fatal: revision walk setup failed
error: https://github.com/Homebrew/homebrew-cask did not send all necessary objects
```
Solution: untap casks as per advice found in issues
Also, don't install coreutils anymore as we're not using `timeout` anymore (this was for when we were testing with `curl`)

Problem: GitHub Actions fails to do the homebrew step

---

pg_yregress/instance.c
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h
pg_yregress/test.c

However, they aren't really tests, and they are executed on demand when an instance is initialized.
Solution: make used instance initialization run as proper tests
Closes #197

Problem: pg_yregress includes instance initialization in TAP tests

---

pg_yregress/docs/usage.md
pg_yregress/instance.c
pg_yregress/pg_yregress.c

When trying to find an error, it's not very helpful as it requires comparing with the original document. And it can't be compared properly at the moment due to the use of references and some other artifacts.
Solution: make TAP the primary output
And make the original output optional. Make sure postgres logs are collected and not printed out together with the TAP output.

Problem: YAML output of pg_yregress

---

cmake/FindPostgreSQL.cmake
extensions/omni_schema/docs/reference.md
extensions/omni_schema/omni_schema--0.1.sql
extensions/omni_schema/tests/fixture/function/4/foo.py
extensions/omni_schema/tests/fixture/function/unavailable/foo.tcl
extensions/omni_schema/tests/test.yml

Writing code in languages that are not SQL inside of SQL iles is a sub-par development experience: syntax highlighting, auto-completion may not work; external tools that work with this languages are unaware of this embedding technique.
It looks like this:
```sql
create function test(a integer) returns bool language plpython3u as $$
return a > 1
$$
```
Solution: allow writing in native language files
omni_schema will find these files and extract SQL function signature in
them and provision these functions from the files, resulting in a proper
development workflow.

Problem: writing non-SQL code in SQL files

---

cmake/FindH2O.cmake

There have been some fixes applied to libh2o in the past weeks.
Solution: upgrade to 398ea25

Problem: using an older version of libh2o

---

extensions/omni_containers/CMakeLists.txt
extensions/omni_containers/omni_containers.c

We use byteswap.h if available, or embed an implementation if not. That's obscuring the code of omni_containers.
Solution: use Postgres' own implementation of these

Problem: conversion of network-order integer

---

pg_yregress/pg_yregress.c

This hides failing connections or other conditions like this.
Solution: ensure we return error code instead of `false` (0)

Problem: pg_yregress bailing returns success

---

cmake/PostgreSQLExtension.cmake
extensions/omni_vfs/CMakeLists.txt
extensions/omni_vfs/docs/reference.md
extensions/omni_vfs/omni_vfs--0.1.sql
extensions/omni_vfs/omni_vfs.c
extensions/omni_vfs/omni_vfs_api--0.1.sql
extensions/omni_vfs/tests/local_fs.yml

omni_vfs uses a technique where we dispatch all FS-specific calls to omni_vfs.method. The problem is that since some of these functions may use types defined in the same schema by the omni_vfs extension, one can't drop the extension without dropping these functions altogether, which may not be a great DX in the sense that if we had to drop/create omni_vfs, we would have to re-create these functions.
Solution: extract omni_vfs types into omni_vfs_api extension
This is not ideal (one more extension) but it does accomplish the job to a degree.
Addresses #219

Problem: omni_vfs method dispatch

---

extensions/omni_vfs/docs/reference.md
extensions/omni_vfs/local_fs.c
extensions/omni_vfs/tests/local_fs.yml

This is difficult to deal with when writing a static HTTP handler because it requires exception handling which is only available in PL/pgSQL or other languages, but not SQL.
Solution: make it return NULL instead
May be not a perfect solution but makes sense for now. May consider a more sophisticated type for it later.

Problem: omni_vfs.file_info errors on file not found

---

extensions/omni_containers/tests/container.yml
extensions/omni_httpd/tests/handler_validity.yml
extensions/omni_httpd/tests/role.yml
extensions/omni_schema/tests/test.yml
extensions/omni_seq/tests/test.yml
extensions/omni_vfs/tests/local_fs.yml
extensions/omni_web/tests/params.yml
extensions/omni_web/tests/query_string.yml
pg_yregress/docs/usage.md
pg_yregress/pg_yregress.c
pg_yregress/test.c
pg_yregress/test.yml
pg_yregress/yaml.c

When we're writing a test and it fails, the resulting output is not very useful. We get `success` set to `false` but it doesn't really give us much. This requires one to go back to the test definition, add an empty `error` key and re-run the test to get the actual error. After figuring the issue out, this change needs to be reverted
This is hardly practical and is annoying. Not to mention that it is confusing that the single concept of failing is managed by two different keys.
Solution: drop `success` altogether
This is achieved by allowing `error` to be set as a boolean if details of the error are not of interest. Thus, one can set `error` to `true` instead of `success` being set to `false`. When `error` is not set, it will be populated with the scalar representation of the error.
During …

Problem: debugging errors in pg_yregress

---

pg_yregress/docs/usage.md
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h
pg_yregress/test.c
pg_yregress/test.yml

Sometimes test organization can be improved if it was easy to group them, without grouping them into a transaction using steps. Otherwise, the structure of the file becomes very flat and it is hard to find different sections.
Solution: introduce test grouping with `tests` test kind
Closes #236

Problem: lack of logical grouping of tests in pg_yregress

---

dynpgext/test/tests/loader_present.yml
extensions/omni_containers/tests/container.yml
extensions/omni_containers/tests/images.yml
extensions/omni_http/tests/test.yml
extensions/omni_httpc/tests/test.yml
extensions/omni_httpd/tests/cascading_query.yml
extensions/omni_httpd/tests/handler_validity.yml
extensions/omni_httpd/tests/http.yml
extensions/omni_httpd/tests/http2_reproxy.yml
extensions/omni_httpd/tests/http_response.yml
extensions/omni_httpd/tests/role.yml
extensions/omni_mimetypes/tests/test.yml
extensions/omni_schema/tests/test.yml
extensions/omni_seq/tests/test.yml
extensions/omni_vfs/tests/local_fs.yml
extensions/omni_web/tests/params.yml
extensions/omni_web/tests/query_string.yml
pg_yregress/docs/usage.md
pg_yregress/pg_yregress.c

This is because we have to name the instance and we get a whole new level of nesting for it.
Solution: allow single instances to be conigured with `instance`

Problem: tedious to configure single instance in pg_yregress

---

.github/workflows/build.yml

```
time="2023-08-23T15:04:26Z" level=warning msg="QEMU binary
\"/Users/runner/.colima/_wrapper/4e1b408f843d1c63afbbdcf80c40e4c88d33509f/bin/qemu-system-x86_64\"
is not properly signed with the \"com.apple.security.hypervisor\"
entitlement"
```
Solution: try upgrading to the latest GitHub Action for setting up Colima

Problem: macos builds on GitHub Actions fail again

---

pg_yregress/test.c

This happens if we have something like this:
```yaml
- tests:
- slect
```
Solution: ensure to mitigate lack of node replacement
Currently, because of lack of node replacement
(https://github.com/pantoniou/libfyaml/issues/84), when scalar nodes are replaced with mapping (containing the error), they are actually removed and a new node is inserted. However, this came into conflict with subtest iteration.

Problem: subtests with a failing scalar test loop indefnitely

---

extensions/omni_schema/docs/reference.md
extensions/omni_schema/omni_schema--0.1.sql

It's kind of pointless. Why? It is not going to affect its storage layout.
Solution: switch it to `text`

Problem: limiting file name extension to 32 characters

---

pg_yregress/instance.c
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h

It is currently ineffective at solving the problem we have in the test setup. If ctest is killed with SIGINT, the children don't catch that, and cleanup is not performed.
Solution: remove this to prevent confusion

Problem: process group stuff in pg_yregress

---

extensions/omni_vfs/CMakeLists.txt
extensions/omni_vfs/docs/reference.md
extensions/omni_vfs/omni_vfs--0.1.sql
extensions/omni_vfs/omni_vfs.c
extensions/omni_vfs/omni_vfs_types_v1--0.1.sql

There are two problems with it:
1. It implies a set of functions for VFS yet doesn't have them
2. Since Postgres schemas are not versioned, it's impossible to depend on diferent versions of VFS types when the ecosystem of filesystem will grow
Solution: rename to omni_vfs_types_v1
`types`, while not perfect, captures the essence of the extension better and versioning the name allows versioned schema for types so that different extensions can depend on different versions if needed.

Problem: omni_vfs_api naming

---

extensions/omni_httpc/omni_httpc.c

```
extensions/omni_httpc/omni_httpc.c:292:10:
warning: incompatible function pointer types
returning 'int (h2o_httpclient_t *, const char *)'
(aka 'int (struct st_h2o_httpclient_t *, const char *)')
from a function with result type 'h2o_httpclient_body_cb'
(aka 'int (*)(struct st_h2o_httpclient_t *, const char *, struct st_h2o_header_t *, unsigned long)') [-Wincompatible-function-pointer-types]
return on_body;
```
Solution: use the most recently introduced signature for `on_body`
One of the recent changes to h2o changed it:
https://github.com/h2o/h2o/commit/a9487cbde08163e540cffcea94c90243c57857a7

Problem: omni_httpc compile-time warning

---

extensions/omni_http/omni_http--0.1.sql

These types are currently unusued and httpd/httpc use their own types. Presence of these types is confusing.
Solution: remove them for the time being
and figure out if we can unite httpd/httpc types later.

Problem: omni_http.http_request and http_response types

---

extensions/omni_httpd/docs/intro.md
extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/tests/http_request.yml

This requires manually creating `http_request` composite type values.
Solution: introduce `omni_httpd.http_request` function that simplifies this type of testing.

Problem: difficult to test request handling

---

extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/tests/handler_validity.yml

This happens when handlers are updated. They are later reported by http worker as invalid.
Solution: ensure we're checking the new record when updated not the old one.
:facepalm:

Problem: report of failing to check httpd handler validity

---

cmake/PostgreSQLExtension.cmake

Some of these invocations complain about `omni_ext` not being available. This requires building it in addition to the component we're focusing on.
Solution: depend on omni_ext

Problem: running `make psql_omni_...` errors out

---

extensions/omni_web/docs/cookies.md
extensions/omni_web/omni_web--0.1.sql
extensions/omni_web/tests/cookies.yml

Cookies are important for session management and doing this manually is not fun.
Solution: provide a basic implementation of the cookie parser
It's probably not the most efficient way to do this, but good enough for start.

Problem: no cookie parser for HTTP handlers

---

extensions/omni_httpc/omni_httpc.c

Solution: ensure event loop is refreshed before firing
It looks like the issue is coming from timers being set longer time ago in the event loop that is shared between invocations.
I am doing this by running one loop run.

Problem: occassional connection timeouts in omni_httpc

---

extensions/omni_httpc/omni_httpc.c
extensions/omni_httpc/tests/test.yml

If we specify `Content-Type: application/json`, we get `Content-Type: Content-Type`
Solution: make sure we send the value, not the name
There was a test covering this functionality but the test was obviously incorrect. Need more eyes!

Problem: omni_httpc request header value is name

---

cmake/FindH2O.cmake

Not a big problem, but a nuisance.
Solution: upgrade to the latest version of h2o
See https://github.com/h2o/h2o/pull/3286

Problem: OpenSSL deprecated API warnigns during h2o compile

---

extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/tests/static/files/test.json
extensions/omni_httpd/tests/static_file.yml

This impedes creation of simple file servers like the ones needed for serving Python packages (hint: upcoming!)
Solution: allow listing of directories (optionally)
Disabled by default.

Problem: static file handler can't list directories

---

extensions/omni_python/omni_python--0.1.sql
extensions/omni_python/tests/functions.yml
extensions/omni_python/tests/types.yml

We can't really set any values to be used during construction:
```python
def my_fun(f):
return f
@my_fun
def ...
```
`my_fun` won't resolve
Solution: execute the whole module on processing
This simplifies things a lot.

Problem: python file loading is cumbersome

---

extensions/omni_httpd/http_worker.c
extensions/omni_httpd/tests/http.yml

If HTTP handler has produced `content-length` header, omni_httpd will add its own based on the size of the response. This creates duplicate headers.
Solution: check for `content-length` in the response
If the size specified is smaller, cut the response body to fit into it to avoid overflow. If the specified size is too large, send a warning but let omni_httpd calculate the right size.
In the end, continue letting h2o handle the header.

Problem: omni_httpd producing duplicate `content-length`

---

cmake/FindH2O.cmake

https://blog.cloudflare.com/zero-day-rapid-reset-http2-record-breaking-ddos-attack/
Solution: update h2o that includes mitigation support
We use `h2o_config_init` so we get the default value of 100ms DoS delay. However, in the future, this parameter should become configurable.

Problem: omni_httpd may be vulnerable to the Rapid Reset attack

---

pg_yregress/CHANGELOG.md
pg_yregress/docs/usage.md
pg_yregress/instance.c
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h

pg_yregress always manages Postgres databases itself.
Solution: allow pg_yregress to be directed against a running instance

Problem: can't use pg_yregress against running databases

---

cmake/FindPostgreSQL.cmake
cmake/OpenSSL.cmake

Solution: ensure we configure it with the right OpenSSL
On macOS, we end up using Homebrew-supplied version of OpenSSL, so lets make Postgres use it.

Problem: pgcrypto is not available in the dev build of Postgres

---

extensions/omni_httpc/omni_httpc.c

I am yet to confirm this in practice, but it is not inconceivable that the buffer will not be initialized when trying to copy from it.
This may result in a segmentation fault.
Solution: guard against this possibility

Problem: omni_httpc may receive an initialized buffer

---

extensions/omni_httpc/omni_httpc.c
extensions/omni_httpc/tests/test.yml

Solution: write a test and document it
While at it, change the behavior to make null header value an empty string instead of skipping the entire header.

Problem: unclear how omni_httpc would handle nulls in headers

---

docs/index.md

- Tiny markdown syntax fix on docs main page: https://docs.omnigres.org/

Doc: fix tiny markdown syntax in Omnigres docs home page

---

extensions/omni_httpc/omni_httpc.c

Solution: ensure body buffer is always properly consumed
When passing a reference to another pointer, and the entire buffer is consumed, the actual buffer was not updated as it changes the pointer to the actual buffer. Now it is updated so things seem to work fine.

Problem: sporadic timeout or I/O errors in omni_httpc

---

extensions/omni_python/omni_python--0.1.sql
extensions/omni_python/tests/functions.yml

If there is a file we're loading and there's a syntax error, it will not do anything but silently accept it.
Solution: throw a syntax error when syntax is invalid
The reason for the original erroneous behavior lies in handling "enriched" and "legacy" approaches to defining stored functions.
In the legacy approach, plpython3u expects a body of the function, which can be syntactically incorrect on its own (like using `return` outside function).
To accommodate that, omni_python was swallowing SyntaxError to let the legacy handler pick the file up.
However, it's obvious that this won't work well when there is a legitimate syntax error.
Now omni_python, if it encounters a syntax error, tries to re-evaluate the code with a function wrapped around it. If it succeeds, we assume that this is a …

Problem: omni_python silently fails on syntax errors

---

languages/python/CMakeLists.txt
languages/python/omni_http/.gitignore
languages/python/omni_http/CMakeLists.txt
languages/python/omni_http/pyproject.toml
languages/python/omni_http/src/omni_http/omni_http.py
languages/python/omni_http/src/omni_http/omni_httpd/__init__.py
languages/python/omni_http/src/omni_http/omni_httpd/flask.py

Solution: integrate omni_httpd with omni_python experience
This change introduces omni_http Python package that integrates with some parts of Omnigres HTTP stack and provides an adapter for Flask applications.
It is fairly crude and is more of a proof of concept at this point.

Problem: impossible to answer HTTP request with Python

---

extensions/omni_httpd/master_worker.c

It will attempt to fall back to effective port even if it is the same port as we just tried to listen at and failed.
Solution: ensure these ports aren't the same
If they are the same, try picking a new port.
(I wonder if we can come up with a good way to test behavior of this?)

Problem: omni_httpd fallback strategy is flawed

---

extensions/omni_schema/omni_schema--0.1.sql

For example, if I have `test.http` file, it will make this notice:
```
NOTICE:  Extension <NULL> required for language <NULL> (required for test.http) is not installed
```
Solution: ignore files for which language can't be found

Problem: notices on files omni_schema doesn't understand

---

extensions/omni_schema/docs/reference.md
extensions/omni_schema/omni_schema--0.1.sql
extensions/omni_schema/tests/fixture/function/1/ignore.sql

It will ingest all files that match a file name pattern.
Solution: provide a way to ignore files
By placing `omni_schema[[ignore]]` somewhere in the file, the file will be ignored.

Problem: omni_schema.load_from_fs is too eager

---

extensions/omni_httpd/omni_httpd--0.1.sql
extensions/omni_httpd/tests/no_init.yml

These shouldn't be created in this case.
Solution: ensure they aren't

Problem: omni_httpd.no_init still creates handlers/listeners

---

pg_yregress/CHANGELOG.md
pg_yregress/docs/usage.md
pg_yregress/pg_yregress.c
pg_yregress/schema.json
pg_yregress/test.yml

Solution: allow to give test suites a name
This is marginally better than comments and gets printed out in the output.

Problem: some test suites' purpose is unclear

---

dynpgext/docs/usage.md
extensions/omni_ext/workers.c
extensions/omni_httpd/master_worker.c

It seemingly attempts to bind the port multiple times and is having difficulties with that.
Solution: ensure it is only omni_ext that manages the lifecycle of omni_httpd and other Dynpgext-registered background workers
Importantly, we do the same for omni_httpd-controlled http_workers as well, otherwise, it exhibits the same problem which manifests in postgres having trouble terminating cleanly afterwards.

Problem:  errors during omni_httpd restart post-crash

---

cmake/FindSTC.cmake

This means we're getting behind on some of the improvements
Solution: upgrade to 4.2
There is a 4.3 pending but it hasn't been released yet. It has some breaking changes, it seems.

Problem: outdated version of STC library

---

extensions/omni_python/omni_python--0.1.sql
extensions/omni_python/tests/functions.yml
extensions/omni_python/tests/omni_python.yml
extensions/omni_python/tests/types.yml
extensions/omni_schema/tests/omni_python.yml

That's because they are set using `set_config`
Solution: persist configuration in omni_python.config
Also, make site_packages default to `data_dir/.omni_python/default` instead of the user's home directory. This way we're not polluting where we shouldn't and when used with Docker, it'll survive in the data volume.

Problem: omni_python configs don't survive the restart

---

extensions/omni_python/omni_python--0.1.sql
extensions/omni_python/tests/functions.yml
languages/python/omni_python/src/omni_python/__init__.py

Sometimes, we need to rename to avoid clashing or otherwise invalid names.
Solution: allow overriding the name using `@pg(name="new_name")`

Problem: impossible to rename @pg-decorated Python functions

---

Dockerfile
extensions/omni_python/.psqlrc
extensions/omni_python/omni_python--0.1.sql
extensions/omni_schema/.psqlrc
languages/python/PythonPackage.cmake

For pre-release scenarios we need to be able to use locally built versions of Python packages. This currently requires running an HTTP endpoint to serve this, and this is a little bit excessive and error-prone.
Solution: use pip's `--find-links` option
This allows us to point to a directory with wheel files. This is not ideal (can we avoid doing anything on the filesystem?) but this is way better than having to have an HTTP endpoint just for this.

Problem: HTTP endpoint to serve local Python packages

---

extensions/omni_python/tests/functions.yml
extensions/omni_python/tests/omni_python.yml
extensions/omni_python/tests/types.yml
extensions/omni_schema/tests/omni_python.yml

This relies on extra index URL for Pip. This is a significant burden for no benefit as we already have `--find-links` support.
Solution: use `pip_find_links` option instead

Problem: omni_python tests use HTTP endpoint

---

Dockerfile
cmake/PostgreSQLExtension.cmake

Even if 5432 is available. This is a nuisance as we need to do `\conninfo` to figure it out.
Solution: pick 5432 if it is available, random otherwise

Problem: `make psql_<component>` always picks a random port

---

extensions/omni_httpd/docs/headers.md
extensions/omni_httpd/tests/http.yml

omni_httpd currently sets it automatically for any non-null response body.
Solution: document it and add a test for null response body behavior.
----
Related to the discussion on https://github.com/omnigres/omnigres/issues/279#issuecomment-1784135868

Problem: omni_httpd content-length behavior is not clear

---

extensions/omni_containers/omni_containers.c

Solution: ensure we pull the `latest` tag
This is not a perfect solution but it helps a lot. In reality, we need to make tags configurable.

Problem: omni_containers have trouble pulling some images

---

languages/python/PythonPackage.cmake

It's just a bit wasteful.
Solution: use one venv for the entire build tree

Problem: Python venv is installed for every Python package

---

extensions/omni_python/tests/omni_python_flask.yml
languages/python/omni_http/src/omni_http/omni_httpd/__init__.py

Fails with an attempt to do `len(None)`
Solution: ensure we handle this case correctly and assume it to be empty

Problem: sending NULL (but not empty) request body to omni_python

---

extensions/omni_aws/migrate/4_s3_list_objects_v2.sql
extensions/omni_aws/migrate/5_s3_put_object.sql
extensions/omni_aws/migrate/7_s3_presigned_url.sql
extensions/omni_aws/tests/minio.yml

Our tests don't try to upload actual (non-textual) binaries. Does the signing work correctly there? We don't have a clear answer to this.
I have a report that at least such requests resulted in a signing error and trying to investigate.
Solution: write a test and ensure it works in a basic case

Problem: do we create correct S3 requests?

---

extensions/omni_python/migrate/2_functions.sql
extensions/omni_python/migrate/3_create_functions.sql
extensions/omni_schema/migrate/4_load_from_fs.sql
extensions/omni_schema/tests/fixture/omni_python/another_module.py
extensions/omni_schema/tests/fixture/omni_python/module1/__init__.py
extensions/omni_schema/tests/fixture/omni_python/module1/submod.py
extensions/omni_schema/tests/fixture/omni_python/test.py
extensions/omni_schema/tests/omni_python.yml

omni_schema + omni_python do not collaborate to provide local imports. One has to resort to providing path-based dependencies through requirements.txt.
Solution: implement a custom importer
The importer requires a (currently janky [1]) integration with omni_vfs.
[1] We can't pass `anyelement` in plpython so we're resorting to pass the textual representation of the fs and its type and then sticking that into a new query. Would having our own fork of plpython resolve this?
--- 
Action plan:

Problem: Python code importing local modules

---

extensions/omni_httpd/migrate/1_basic_types.sql

We all want omni_httpd to be as fast as possible
Solution: mark commonly used functions immutable as an optimization
Measured a ~3% improvement on a simple static response test.

Problem: fast is never fast enough

---

Dockerfile

Building Docker image sometimes fails with:
```
#53 0.355 E: Package 'wget' has no installation candidate
#53 0.355 E: Package 'build-essential' has no installation candidate
#53 0.355 E: Unable to locate package clang
#53 0.355 E: Unable to locate package lld
#53 0.355 E: Package 'flex' has no installation candidate
#53 0.355 E: Unable to locate package libreadline-dev
#53 0.355 E: Package 'zlib1g-dev' has no installation candidate
#53 0.355 E: Package 'libssl-dev' has no installation candidate
#53 0.355 E: Unable to locate package lldb
#53 0.355 E: Package 'gdb' has no installation candidate
#53 0.355 E: Package 'make' has no installation candidate
#53 0.355 E: Package 'perl' has no installation candidate
#53 0.355 E: Package 'python3-dev' has no installation candidate
#53 0.355 E: …
```

Problem: apt command is unstable

---

cmake/PostgreSQLExtension.cmake

This is because we use `sort -n` on the relative file paths, not just on the file names.
```shell
$ ls extensions/omni_python/migrate/*.sql | sort -n
extensions/omni_python/migrate/12_test_sorting.sql
extensions/omni_python/migrate/1_config.sql
extensions/omni_python/migrate/2_functions.sql
extensions/omni_python/migrate/3_create_functions.sql
extensions/omni_python/migrate/4_execute.sql
extensions/omni_python/migrate/5_install_requirements.sql
```
Solution: Use version sort instead of numeric sort.
```shell
$ ls extensions/omni_python/migrate/*.sql | sort -V
extensions/omni_python/migrate/1_config.sql
extensions/omni_python/migrate/2_functions.sql
extensions/omni_python/migrate/3_create_functions.sql
extensions/omni_python/migrate/4_execute.sql …
```

Problem: Migrations are not sorted in order of versions

---

extensions/omni_python/migrate/2_functions.sql
extensions/omni_python/tests/functions.yml

Currently, if we want to expose a callable to Postgres, we have to do something like this:
```python
thing_ = Thing()
def thing(in: int) -> int:
return thing_(in)
```
This is particularly common for Flask integration.
While certainly doable, it is a bit annoying/redundant.
Solution: make any callable a fair game
Now it is possible to wring the code above as:
```python
thing = pg(Thing())
```

Problem: wrapping callables in Python is a bit annoying

---

extensions/omni_python/docs/intro.md
extensions/omni_python/migrate/2_functions.sql
extensions/omni_python/tests/omni_python_flask.yml

At the time of the loading a Python file with such import, we'd get the following error:
```
RuntimeError: Working outside of request context.
This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
```
Solution: don't consider callables without any attributes
If a callable has an empty `dir`, then there's no `__pg_stored_procedure__ and we can avoid calling `hasattr` which triggers the above error.

Problem: importing request from flask

---

.github/workflows/build.yml
cmake/FindPostgreSQL.cmake
extensions/omni_ext/init.c
extensions/omni_ext/omni_ext.c
extensions/omni_ext/omni_ext.h
extensions/omni_ext/workers.c
extensions/omni_httpc/omni_httpc.c
extensions/omni_httpc/tests/test.yml
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/omni_httpd.c

This happens if Postgres is built with assertions enabled.
Solution: enable assertions and figure out the crashes
1. Ensure we always set hash element type (there are assertions checking for defaults)
2. Ensure we allocate background worker handles in top memory context to avoid reclaiming them too early.
3. Ensure we restore user and security context after committing transactions (abort reverts them, commit doesn't)
Also, discovered a case when omni_httpc client is used with null queries only: it'll crash. Avoid doing anything on requests if there are no actual requests to make.
Importantly, this makes Postgres builds slower and these are not as suitable for benchmarking as before. However, correctness being more important, this is a better default for development.

Problem: reports of omni_ext/httpd crashing postgres

---

extensions/omni_python/CMakeLists.txt

Can't find omni_httpd.
Solution: ensure omni_httpd is required for omni_python tests

Problem: omni_python Flask tests may fail to start

---

.github/workflows/build.yml

For example, see #315: http2_reproxy test often fails, and it may be because of a slow machine.
Solution: use BuildJet runners for general builds

Problem: flaky tests

---

cmake/FindPostgreSQL.cmake

With this, a debug build would be assumed, but the directory for Postgres build will contain an empty build type (`Linux-` instead of `Linux-Debug`)
Solution: ensure the fall back is Debug

Problem: not specifying CMAKE_BUILD_TYPE

---

cmake/PostgreSQLExtension.cmake
cmake/Version.cmake

If we don't trigger cmake rerun, it won't assign new versions based on Git revision to extensions. This is problematic as versions becomes desynchronized.
Solution: always trigger a reconfigure if Git revision changes

Problem: rebuilding extensions doesn't change their git version

---

extensions/omni_httpc/omni_httpc.c
extensions/omni_httpc/tests/test.yml

Solution: ensure we test it for null before detoasting

Problem: omni_httpc.http_execute crashes if URL is NULL

---

extensions/omni_aws/migrate/3_s3.sql
extensions/omni_aws/tests/minio.yml

For example, whem using PutObject and setting path to `test` it will error out with a malformed request.
Solution: ensure we always have a leading slash there

Problem: setting path to some AWS S3 functions without /

---

.github/workflows/build.yml

The error looks like this:
```
dyld[62749]: Library not loaded: /Users/ci/actions-runner/_work/omnigres/omnigres/.pg/Darwin-Release/16.1/build/lib/libpq.5.dylib
Referenced from: <9334436C-BA46-32DC-873D-CAAE0C09F2A1>
/Users/ci/actions-runner1/_work/omnigres/omnigres/build/pg_yregress/pg_yregress
```
Solution: ensure we only use cached builds from the space path
Bascially, we have two action runners, in $HOME/actions_runner and $HOME/actions_runner1 and when they get .pg restored from the action cache, the libraries that get built in one (like libpq) have install_name that contains a full path to where it was built. Thus. When we have `actions_runner/_work/omnigres/omnigres/.pg/.../libpq.dylib` and then restore it as `actions_runner1/_work/omnigres/omnigres/.pg/.../libpq.dylib` and link …

Problem: sporadic failures in macOS CI

---

extensions/omni_aws/migrate/4_s3_list_objects_v2.sql
extensions/omni_aws/migrate/5_s3_put_object.sql
extensions/omni_aws/migrate/6_s3_create_bucket.sql

Seemingly everything (with the exception signed) URLs doesn't work with the digitalocean_s3_endpoint() backend, returning a signature mismatch error
Solution: set null path to '/' for methods with optional paths and send empty payload for create bucket because DigitalOcean rejects it
#391

Problem: omni_aws DigitalOcean S3 support

---

pg_yregress/CHANGELOG.md
pg_yregress/docs/usage.md
pg_yregress/instance.c
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h
pg_yregress/schema.json
pg_yregress/test.c
pg_yregress/test.yml

In some obscure cases (like omni_ext), we want to be able to test against multiple databases.
Currently, we can't do create database because we're wrapping everything into a transaction (CREATE DATABASE cannot run inside a transaction block error), and we can't switch databases on the fly (pg_yregress doesn't have support for it).
Solution: add transaction and database properties to pg_yregress test spec
setting `database` to a database name will create a connection to the specified database and close it at the end of the test
setting `transaction` to false (default is true) will not execute a `BEGIN` statement before running the test queries
#351

Problem: impossible to run tests in a different database

---

cmake/FindH2O.cmake

There are some issues with it:
* it `abort()`s on some errors instead of calling h2o_fatal()
* recent security advisories
Solution: upgrade to the latest version
* https://github.com/h2o/h2o/pull/3323
* https://github.com/h2o/h2o/security/advisories/GHSA-2ch5-p59c-7mv6
* https://github.com/h2o/h2o/security/advisories/GHSA-5v5r-rghf-rm6q

Problem: outdated H2O version

---

extensions/omni_sql/deparse_16.c

The current deparse_16.c file was made to be just good enough to support postgres 16. It hasn't been maintained and it could be imperfect.
Solution: The libpg_query library already has its own deparse file for postgres 16. The changes in this commit updates our current deparse_16.c with the postgres_deparse.c from libpg_query library's 16-latest branch.
Closes:
#411

Problem: Query Unparsing for postgres 16 may be imperfect

---

.github/workflows/build.yml

We are experiencing these way more often in CI than in development.
While the underlying issues do have to get solved, these issues do slow down development of other features or bugfixes as they require us to re-run tests until they succeed.
Solution: make ctest try to repeat tests until they pass
This is not a perfect solution (a perfect one would be fixing the issues), but it'll hopefully give us some breathing room.

Problem: random tests failures in CI

---

cmake/PostgreSQLExtension.cmake
pg_yregress/CHANGELOG.md
pg_yregress/docs/usage.md
pg_yregress/instance.c
pg_yregress/pg_yregress.c
pg_yregress/pg_yregress.h
pg_yregress/schema.json
pg_yregress/test.yml

omni_vfs table_fs tests failed due to inconsistent sort ordering of text between my machine and CI runners.
The reason turned out to be different LC_COLLATE(responsible for String sort order) was different en_US.UTF-8 (on my machine) and C.UTF-8 (on CI runners) because initdb will initialize the database cluster with the locale setting of its execution environment by default.
Solution: explicitly set encoding and locale for initdb to avoid any surprises
Closes #416

Problem: locale setting of database is dependent on environment

---

cmake/OpenSSL.cmake

And we only need it to configure OpenSSL.
Solution: don't build it unless there's at least Perl 5.10 (as requested by NOTES-PERL.md in OpenSSL)
Also disable installing `Text::Template` as it seems to pick up a fallback version fron the repo.

Problem: building Perl for OpenSSL may take long

---

extensions/omni_httpd/tests/http2_reproxy.yml

This is the test: https://github.com/omnigres/omnigres/blob/master/extensions/omni_httpd/tests/http2_reproxy.yml
It often fails due to a timeout in CI, and we have to re-run it.
The behaviour it is testing is as follows:
Considering that we have only two workers (https://github.com/omnigres/omnigres/blob/master/extensions/omni_httpd/tests/http2_reproxy.yml#L6)
If we send two HTTP/2 requests over the same connection, instead of blocking on the second request (since the Postgres worker is busy), omni_httpd will reproxy the request to the other available worker.
It is tested by making the backend sleep for 2 seconds. The test ensures that it takes no longer than 2.5 seconds total responses return different pids for their backends.  I wondered if this can be tested better (preferably without …

Problem: intermittent CI problem with http2_reproxy

---

Dockerfile
cmake/OpenSSL.cmake

Currently there is a problem building OpenSSL for a container, something with OpenSSL:
```
/usr/bin/ld: libpq/be-secure-openssl.o: in function `be_tls_open_server':
be-secure-openssl.c:(.text+0x1032): undefined reference to `SSL_get1_peer_certificate'
/usr/bin/ld: libpq/be-secure-openssl.o: in function `my_SSL_set_fd':
be-secure-openssl.c:(.text+0x1bd9): undefined reference to `ERR_new'
/usr/bin/ld: be-secure-openssl.c:(.text+0x1bf1): undefined reference to `ERR_set_debug'
/usr/bin/ld: be-secure-openssl.c:(.text+0x1c0a): undefined reference to `ERR_set_error'
/usr/bin/ld: be-secure-openssl.c:(.text+0x1c2b): undefined reference to `ERR_new'
/usr/bin/ld: be-secure-openssl.c:(.text+0x1c43): undefined reference to `ERR_set_debug'
/usr/bin/ld: be-secure-openssl.c:(.text+0x1c5c): undefined …
```

Problem: building OpenSSL in a container

---

HACKING.md
cmake/PostgreSQLExtension.cmake

Currently it's impossible to configure the databases `psql_` targets create. However, this is very limiting because sometimes we want to use them with a particular configuration.
Solution: use postgresql.conf and pg_hba.confi if provided

Problem: configuring psql target dbs

---

extensions/omni_ext/init.c
extensions/omni_ext/omni_ext.c
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/master_worker.c

Observed a segmentation fault preparing background worker records in omni_ext.
Solution: ensure static initialization of global containers
Valgrind indicated use of stack-allocated uninitialized values, and this has led to changes in how we initialize global containers to ensure we don't run into this problem.

Problem: in release mode, omni_ext/omni_httpd might crash

---

Dockerfile
docker/entrypoint.sh

When a user experiences a problem, a crash or something of the kind,
it's difficult to figure out what happened.
Solution: enable Tailscale integration
When Tailscale auth key is specified, it'll connect to the appropriate
Tailnet and remote access to the instance will be possible.
This also changes the settings and adds some tools (like lldb, valgrind, etc.) to make it more debuggable.

Problem: debugging remote Omnigres

---

extensions/omni_var/omni_var.c
extensions/omni_var/tests/variables.yml

Solution: ensure we don't create a new hashtable entry when we search for a variable.

Problem: omni_var.get crashes with SIGSEGV

---

cmake/PostgreSQLExtension.cmake

Fails preloading these extensions as they are specified without a path when running `make psql_<EXTENSION>`
Solution: include path to the shared file

Problem: SHARED_PRELOAD ON in extensions

---

cmake/PostgreSQLExtension.cmake

If an extension is not a dynpgext extension, we need to be able to load it without omni_ext. But we don't know the filename because it contains a version.
Solution: pass `EXTENSION_FILE` environment variable to pg_yregress
It can now be used as `*/env/EXTENSION_FILE` in the test

Problem: preloading some extensions in tests

---

HACKING.md
cmake/PostgreSQLExtension.cmake

One problem with `make psql_<EXT>` workflow is that it re-initializes a database every time it start. This makes it hard to explore scenarios that require restarting the database and still having the same data.
Solution: introduce PSQLDB environment variable
Specifying this variable instructs the aforementioned `psql` targets to use a specific location for the database and don't wipe it.

Problem: manually trying certain behaviours between restarts

---

cmake/PostgreSQLExtension.cmake

It fails because `CMAKE_CURRENT_BINARY_DIR/data` might not exist.
Solution: ensure it does

Problem: mktemp -d may fail in `psql_<EXT>`

---

generate-upgrades.sh

It's problematic as there are no upgrade scripts.
Solution: generate upgrade scripts "on demand"
The general idea here is that we can compare the installations of each version and find the source code of which functions were changed. We can also see which part of the incremental migration was added.
What we haven't considered here yet is what happens if the version introduces additional function signatures to the schema. Ideally, they shouldn't do this as part of `src` includes but in a new incremental migration.
This implies that we no longer permit arbitrary changes in incremental migrations between releases. They have to be incremental. The only thing that stays away from this is the code of the functions.
---
This is not yet a complete answer to the upgradeability problem, but we're …

Problem: upgrading between arbitrary versions of extensions

---

.github/workflows/build.yml

Context: It looks like scheduled builds were introduced to keep the [GitHub build cache warm](https://github.com/omnigres/omnigres/commit/95e1d839992aa587fe47029bfd2b5387b44eb608). Later an approval step was introduced to the workflow which requires approval even for the scheduled builds, which results in those scheduled builds not being run without manual approval.
Solution: Run scheduled builds on the `master` environment. 
Alternative Solution: Alternatively we can delete the scheduled cron because this particular workflow has been migrated to Warp and FlyCI.
_P.S.: I'm one of the co-founders of [FlyCI](https://www.flyci.net/)._

Problem: Scheduled Builds require approval

---

pg_yregress/CHANGELOG.md
pg_yregress/test.c

Under some circumstances (while developing Logtalk integration) pg_yregress tests with `params` were (oddly) returning results that were containing a portion of the test suite file.
Solution: ensure param scalars are constrained by their length before sending them off to Postgres.
Not doing so opens up the problem of pointing to the whole file's content.

Problem: seeing superfluous data in pg_yregress test results

---

.github/workflows/clang-format.yml
extensions/omni_ext/control_file.h
extensions/omni_httpd/http_worker.c

We were stuck with clang-format 15 for a while and (for example), on homebrew it is now 17.
Solution: switch to 17
I have to rename `requires` as 17 formats it differently now.

Problem: older clang-format

---

extensions/omni_ext/control_file.c
extensions/omni_httpd/master_worker.c
extensions/omni_httpd/migrate/6_unload.sql
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/omni_httpd.h
extensions/omni_httpd/tests/unloading.yml

There is no way to stop it to load another version of the extension.
Solution: use omni_ext unloading to kill the master worker
The master worker's PID is set by the master worker itself upon startup.
Also fixes a bug in omni_ext that wouldn't really unload anything that was already loaded during startup.
This is not a complete end-to-end solution to upgrading omni_httpd, but it is definitely a component to it.

Problem: upgrading omni_httpd in runtime

---

extensions/omni_ext/init.c

It tries to initialize PGC_POSTMASTER variables and do other things that can only be done during shared preloading.
Solution: don't try to initialize omni_ext unless being preloaded

Problem: loading omni_ext without preloading

---

extensions/omni_schema/src/migrate_from_fs.sql
extensions/omni_schema/tests/fixture/natsort/04_.sql
extensions/omni_schema/tests/fixture/natsort/1_.sql
extensions/omni_schema/tests/fixture/natsort/2_.sql
extensions/omni_schema/tests/fixture/natsort/33_.sql
extensions/omni_schema/tests/fixture/natsort/3_.sql
extensions/omni_schema/tests/fixture/natsort/5_.sql
extensions/omni_schema/tests/test.yml

For example, `33_descr` may precede `3_descr`. Also, zero-prefixed numbers will misplace ordering as well.
Solution: ensure omni_schema.migrate_from_fs uses natural sorting

Problem: omni_schema migrations are not always ordered correctly

---

dynpgext/docs/usage.md
dynpgext/dynpgext.h
extensions/omni_ext/init.c
extensions/omni_ext/omni_ext.c
extensions/omni_ext/omni_ext.h
extensions/omni_ext/test/migrate/omni_ext_test_no_preload/omni_ext_test_no_preload.sql
extensions/omni_ext/test/omni_ext_test.c
extensions/omni_ext/test/tests/omni_ext_test_no_preload/bgw.yml
extensions/omni_ext/workers.c
extensions/omni_httpd/omni_httpd.c

When an extension is not preloaded, database-local workers are not started since we need to scan extensions in different databases.
Solution: use a shared table to list background worker requests
This also avoids the need for a rather convoluted rendezvous we had.
I got rid of callbacks in background worker registration. While this has worked for workers initialized during the initial startup phase, this has become increasingly more complex for runtime-started workers. Problem is that we can't simply point to the function or the callback payload if they weren't loaded and prepared during the startup phase in the parent process. To date, this capability hasn't been used and, as far as I can tell, it doesn't provide any extra functionality that can't be achieved by executing that logic in …

Problem: omni_ext does not start database-local workers in runtime

---

extensions/omni_ext/init.c
extensions/omni_ext/omni_ext.h
extensions/omni_ext/test/migrate/omni_ext_test/omni_ext_test.sql
extensions/omni_ext/test/migrate/omni_ext_test_no_preload/omni_ext_test_no_preload.sql
extensions/omni_ext/test/omni_ext_test.c
extensions/omni_ext/test/tests/omni_ext_test/tests.yml
extensions/omni_ext/test/tests/omni_ext_test_no_preload/bgw.yml

Specifically, the test for global background worker for preloaded extensions pre-creates a table in its schema and the table is used as a marker. So it never really tests it.
Also, to add, recent change that passed db_oid to global worker won't work during preloading as `MyDatabaseId` at that time is 0 (if it is actually initialized at the time we prepare the background worker entry)
Solution: introduce some "reserved" space in SharedInfo of omni_ext
This is a strictly internal hack for the time being that allows tests to have a shared location in memory to write something to.
The test will now write a flag there once the global background worker is started. A new utility function has been added to track that.
This could have been done better, but I am a bit tired and I need this to work …

Problem: omni_ext background worker startup not tested correctly

---

extensions/omni_ext/CMakeLists.txt
extensions/omni_ext/control_file.c
extensions/omni_ext/hooks.c
extensions/omni_ext/init.c
extensions/omni_ext/omni_ext.c
extensions/omni_ext/omni_ext.h
extensions/omni_ext/test/CMakeLists.txt
extensions/omni_ext/test/omni_ext_test.c
extensions/omni_ext/test/tests/omni_ext_test/rollback.yml
extensions/omni_ext/test/tests/omni_ext_test/tests.yml
extensions/omni_ext/test/tests/omni_ext_test/update.yml
extensions/omni_ext/test/tests/omni_ext_test_no_preload/bgw.yml
extensions/omni_ext/test/tests/omni_ext_test_no_preload/no_preload.yml
extensions/omni_ext/tests/tests.yml
extensions/omni_ext/workers.c
extensions/omni_httpc/tests/test.yml
extensions/omni_httpc/tests/timeout.yml

Currently, we require 1+N_of_database workers to simply load background workers into any database that has a particular extension requiring database-local background workers. This is, frankly, wasteful.
Solution: hook into process utility statements
This allows us to capture extension and database creation to drive necessary provisioning of resources like database-local background workers.
This also opens a way to handle unloading and updating extensions the same way, transparently to the extensions, they wouldn't need `load/unload` anymore.

Problem: running additional workers in omni_ext

---

cmake/PostgreSQLExtension.cmake
extensions/omni_ext/hooks.c
extensions/omni_manifest/docs/usage.md
extensions/omni_manifest/migrate/4_artifact_functions.sql
extensions/omni_manifest/migrate/5_requirement_status_kept.sql
extensions/omni_manifest/src/artifact_to_json.sql
extensions/omni_manifest/src/artifact_to_jsonb.sql
extensions/omni_manifest/src/artifact_to_text.sql
extensions/omni_manifest/src/artifacts_to_json.sql
extensions/omni_manifest/src/artifacts_to_jsonb.sql
extensions/omni_manifest/src/artifacts_to_text.sql
extensions/omni_manifest/src/install.sql
extensions/omni_manifest/src/install_plan.sql
extensions/omni_manifest/src/json_to_artifact.sql
extensions/omni_manifest/src/json_to_artifacts.sql
extensions/omni_manifest/src/jsonb_to_artifact.sql
extensions/omni_manifest/src/jsonb_to_artifacts.sql
extensions/omni_manifest/src/text_to_artifact.sql
extensions/omni_manifest/src/text_to_artifacts.sql
extensions/omni_manifest/tests/artifact.yml
extensions/omni_manifest/tests/install.yml

It's still difficult to just take a version of Omnigres and install or upgrade a set of extensions from it.
Solution: provide exchange formats for artifact listing
Manifests are effectively artifact lists, so we now support text and JSON formats for describing artifacts. Omnigres build process produces such artifact lists upon each build (`artifacts.txt`).
The delivery of this file may depend on a particular process as we don't have a common one established yet. One can put it onto the file system and read it with `pg_read_file`, or can download it using `omni_httpc` (if they have it already, that is).
Quite a lot going on in this change besides this:
* It fixes an issue with omni_ext hooks incorrectly handling the case of an attempt to upgrade version of an extension to the same version, …

Problem: installing a set of Omnigres extensions

---

extensions/omni_ext/hooks.c
extensions/omni_ext/test/tests/omni_ext_test/update_same_explicit.yml
extensions/omni_ext/test/tests/omni_ext_test/update_same_implicit.yml

There are two cases I can think of right now:
1. `alter extension update to 'VER'` where the current version is `VER`
2. `alter extension update` where the default and the current versions are both `VER`
Solution: write tests for these cases
Fix the second case as it didn't work correctly and was causing an error as omni_ext tried to unload in this case.

Problem: is omni_ext handling all extension update edge cases?

---

extensions/omni_ext/hooks.c

Using strncmp over there does not correctly compare strings as it effectively compares substrings.
Solution: use strcmp in those cases instead

Problem: wrong string comparison in omni_ext's hooks

---

extensions/CMakeLists.txt
extensions/omni_aws/CMakeLists.txt
extensions/omni_containers/CMakeLists.txt
extensions/omni_ext/CMakeLists.txt
extensions/omni_ext/test/CMakeLists.txt
extensions/omni_http/CMakeLists.txt
extensions/omni_httpc/CMakeLists.txt
extensions/omni_httpd/CMakeLists.txt
extensions/omni_json/CMakeLists.txt
extensions/omni_manifest/CMakeLists.txt
extensions/omni_mimetypes/CMakeLists.txt
extensions/omni_os/CMakeLists.txt
extensions/omni_python/CMakeLists.txt
extensions/omni_schema/CMakeLists.txt
extensions/omni_seq/CMakeLists.txt
extensions/omni_sql/CMakeLists.txt
extensions/omni_txn/CMakeLists.txt
extensions/omni_types/CMakeLists.txt
extensions/omni_var/CMakeLists.txt
extensions/omni_vfs/CMakeLists.txt
extensions/omni_web/CMakeLists.txt
extensions/omni_xml/CMakeLists.txt

I've noticed that if I checkout a copy of Omnigres inside of my working directory of Omnigres (two levels below: 'omnigres/path/checkout') it would grab CMake includes from the working directory instead of the new clone.
Solution: ensure we include relative to the CMakeLists.txt file

Problem: building extensions sometimes grabs wrong includes

---

extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/tests/create_drop.yml
extensions/omni_httpd/tests/unloading.yml

The sequence below tends to (always?) lock up at `drop` waiting for the master worker to die and it never does.
```postgresql
create extension omni_httpd cascade; drop extension omni_httpd;
```
Solution: ensure we're not holding onto the transaction with catalog changes
We do this by awaiting for master worker termination at the point when all changes are visible and transaction's memory context is being deleted.

Problem: dropping omni_httpd in quick succession to create

---

extensions/omni_ext/omni_ext.c

The error is: "cannot read pg_class without having selected a database"
Solution: ensure we start the worker with the correct database OID
Turned out that in some cases, we were going through the `register_bgworker_runtime` path and it was not registering the intended description of the background worker (`local_bgw`) but the original one that didn't have a correct main argument set.
With this change, it bow registers the correct one.
This applies to other dynpgext components beyond omni_httpd.

Problem: occassional FATAL error in omni_httpd's master worker

---

extensions/omni_ext/control_file.c
extensions/omni_ext/omni_ext.c
extensions/omni_ext/omni_ext.h

This leads to odd errors like:
```
ERROR: could not access file "/home/runner/work/omnigres/omnigres/s3_extensions/16/09a1406/build/extensions/omni_ext/omni_ext.master_worker": No such file or directory
```
Solution: ensure it gets a fitting name, too

Problem: omni_ext's library path might not fit BGWLEN-1

---

.github/workflows/ext-scripts.yml
cmake/PostgreSQLExtension.cmake
dynpgext/test/CMakeLists.txt
extensions/omni_ext/test/CMakeLists.txt
generate-upgrades.sh
libpgaug/test/CMakeLists.txt

This is because we use directory tree for discovery, and some extensions share the directory (like omni_vfs_types_v1).
Solution: build extension/path mapping during build
Also, build these artifacts on-demand and store them in S3.

Problem: generate-upgrades.sh doesn't consider all extensions

---

Dockerfile
cmake/PostgreSQLExtension.cmake
generate-upgrades.sh

It clashes with CPack when it is used.
Solution: rename it to `package_extensions`

Problem: `package` target name

---

extensions/omni_manifest/docs/usage.md

There is a public s3 endpoint available to download extension update scripts but there is no documentation available on how to use it.
Solution: Add a section to `omni_manifest` docs to demonstrate update of extensions to newer versions.

Problem: update of extensions to newer versions is unclear

---

extensions/omni_httpd/docs/intro.md
extensions/omni_httpd/master_worker.c
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/omni_httpd.h
extensions/omni_httpd/tests/create_drop.yml

Solution: use temp directory to store omni_httpd unix socket file
#479

Problem: pg_rewind fails in presence of omni_httpd extension files in postgres data directory

---

extensions/omni/hook_harness.c

It uses `done` to exit the loop because breaking from loop wouldn't work inside of the `case` statement.
There's some indirection here (set variable, check its value) and extra operations where all we want is just to exit from the loop.
Solution: use a goto to finalize hook iteration

Problem: omni's iterate_hook use of an extra variable

---

cmake/FindPostgreSQL.cmake

When using Cmake to compile Omnigres, there is no ability to pass in compiler optimization flags. This is an issue because it can greatly slow down performance for release versions on Omnigres.
Solution: pass CMake's build-type-specific cflags to Postgres

Problem: CMake cannot pass compiler optimization flags

---

.github/workflows/ext-scripts.yml

The workflow is not creating any extension release files when triggered on pull_request_target event due to incorrect usage of github context.
Solution: Fix it

Problem: Extension scripts workflow output is wrong on pull_request_target event

---

.github/workflows/ext-scripts.yml
generate-upgrades.sh

`generate-upgrades.sh` script is not working because it still uses unversioned `omni.so`.
Solution: Use versioned `omni--<version>.so` file in the script.
Also fixed PR warnings and made the script portable to work on both macos and ubuntu.

Problem: Generate upgrades script is broken

---

README.md
extensions/omni_manifest/docs/usage.md

Docs still reference commit SHA versioned extensions which is no longer be maintained after the move to semver releases of extensions.
Solution: Update the docs with the current method of downloading and installing omnigres extensions.

Problem: Docs for omnigres extensions download is outdated

---

download-omnigres-extension.sh
extensions/omni_manifest/docs/usage.md

Currently, downloading an omnigres extension involves few steps like downloading and copying the extension files in the right postgres directories which is not a good from user experience perspective.
Solution: Write a bash script to encapsulate all the stuff described above to simplify omnigres extension download.

Problem: omnigres extension download is not straightforward

---

.github/workflows/build.yml
CONTRIBUTING.md

Now that we're switching away from ongoing development in `master` to "next" branches to avoid leaking unreleased versions, PRs to the "next" branches aren't checked against in GitHub Actions.
Solution: enable testing of the "next" branches

Problem: no running tests in "next" versions

---

.github/workflows/ext-scripts.yml

Omnigres extensions can only be released on merge to master so running it for PRs to non master branches doesn't make sense. Any mistakes regarding releases will eventually be caught in PR to master anyways.
Solution: trigger it only on PR to master

Problem: Extension scripts workflow runs on non-release PRs

---

extensions/omni/hook_harness.c
extensions/omni/init.c
extensions/omni/omni.c
extensions/omni/omni_common.h

This doesn't match the signature in `omni` which has no return value as we're collecting return values in the hook handle.
Solution: change it to `void`
and make it a bit harder to supply wrong signature syntactically by forcing visual alignment of the type names.

Problem: default_needs_fmgr returns `bool`

---

docker/initdb-slim/001-settings.sql
docker/initdb/001-settings.sql

Unversioned omni shared object is set in
`shared_preload_libraries` which is no
longer present.
Solution: use versioned `omni--x.y.z.so` instead
This is just a temporary fix as updating
version in sql scripts file each time new
omni version is released is not ideal.

Problem: omnigres docker image fails to run

---

extensions/omni/init.c
extensions/omni/omni.c

When starting omni's own background workers when `omni` the extension is installed with a version that is not matching the version preloaded, it'll error out and everything will shut down.
Solution: issue a warning in background workers instead
This is not a [perfect] fix but rather a temporary mitigation.

Problem: background worker failure to load old omni

---

extensions/omni/init.c
extensions/omni/omni.c
extensions/omni/omni_common.h
extensions/omni/test/tests/dsa.yml

This error is happening after some use of omni_httpd.
Solution: use a single DSA
The crux of the problem:
* Number of DSMs is very limited: https://github.com/postgres/postgres/blob/master/src/backend/storage/ipc/dsm.c#L195-L196
* We pin DSAs in each backend so that other backends can use memory allocated there even if those backends exit
* These numbers run out pretty fast, resulting in the error. A new connection, upon being established, creates a new DSA, therefore making us come closer to the limit.
* The problem here is that we don’t release these DSA/DSMs ever and hit the limits pretty soon as we store pointers
This is unsustainable.
Instead, we now use a single DSA initialized by the first backend and let other backends attach to it. New DSMs will still be created but at a much …

Problem: "too many dynamic shared memory segments"

---

docker/initdb-slim/001-settings.sql
docker/initdb/001-settings.sql

0.1.2, however, contains an important fix.
Solution: switch images to omni 0.1.2

Problem: docker images still sport omni 0.1.1

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/event_loop.c
extensions/omni_httpd/event_loop.h
extensions/omni_httpd/http_worker.c

This is manifesting in scenarios like recursive HTTP calls (HTTP handler calling back into the same instance of omni_httpd) and having omni_httpd not receive an opportunity to accept an incoming connection.
Solution: fix a bug in socket read resumption
Previously, what we attempted in ae72953f406d8716741f0c24f08b0e51321ca20a was subtly (and critically)
wrong. Specifically, we were trying to resume reading from a socket that was holding the worker busy. 
However, that's not the socket that needs resumption, as we actually need to resume all other sockets that
were, in fact, stopped.

Problem: omni_httpd worker sporadically stops listening

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/http_worker.c

```
* thread #1, name = 'postgres', stop reason = signal SIGSEGV
* frame #0: 0x00007f5b5609ae94 libc.so.6`___pthread_mutex_lock(mutex=0x0000000000000010) at pthread_mutex_lock.c:80:23
frame #1: 0x00007f5b4bf4800e omni_httpd--0.1.2.so`h2o_multithread_send_message(receiver=0x00007f5b4c516320, message=0x0000000000000000) at multithread.c:196:5
frame #2: 0x00007f5b4bf40038 omni_httpd--0.1.2.so`sigusr2 at http_worker.c:85:3
```
Solution: ensure unblocking signals after the setup
Originally, we unblocked signals before `event_loop_thread` was set up and given an early SIGUSR2, it would fail to work correctly.
Thanks to @rmodpur for discovering the issue

Problem: omni_httpd may crash in SIGUSR2 handler

---

extensions/omni_sql/CHANGELOG.md
extensions/omni_sql/migrate/3_raw_statement.sql
extensions/omni_sql/omni_sql.c
extensions/omni_sql/tests/omni_sql/raw_statements.yml

Basically, if we try to use `omni_sql.statement` to parse a multiple statement expression (`select 1; select 2`) we end up with de-parsed multiple statement expression we can't split.
This prevents us from splitting source files into individual statements.
Solution: introduce "raw statement" parsing
A raw statement is the original source of the statement with its location in the original string (line and col, as offsets are not practically useful).
Using `raw_statements` function one can split a string into multiple statements, while retaining their original formatting and location.
Now, for any further processing, the obtain source can be converted into a `omni_sql.statement`.

Problem: iterating over parsed SQL statements

---

extensions/omni_sql/CHANGELOG.md
extensions/omni_sql/migrate/4_statement_type.sql
extensions/omni_sql/omni_sql.c
extensions/omni_sql/tests/omni_sql/statement_type.yml

This makes it difficult to discern their potential impact.
Solution: add `statement_type` function returning an enum value

Problem: how do we distinguish omni_sql-parsed statements?

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/http_worker.c

```
* thread #1, name = 'postgres', stop reason = signal SIGSEGV
* frame #0: 0x000062280afab8c2 postgres`ReleaseCatCache(tuple=0x0000000000000000) at catcache.c:1461:2
frame #1: 0x000062280afc9253 postgres`ReleaseSysCache(tuple=0x0000000000000000) at syscache.c:868:2
frame #2: 0x00007f9d14b40b7f omni_httpd--0.1.2.so`http_worker(db_oid=16610) at http_worker.c:359:25
frame #3: 0x000062280ad04375 postgres`StartBackgroundWorker at bgworker.c:861:2
```
Solution: avoid releasing the cache if role's tuple is invalid

Problem: omni_httpd crashes if a desired role is not available

---

extensions/omni/hook_harness.c
extensions/omni/hook_types.h
extensions/omni/init.c
extensions/omni/omni_common.h
extensions/omni/test/hooks.c
extensions/omni/test/hooks.h
extensions/omni/test/omni_test.c
extensions/omni/test/tests/hooks_coverage.yml
omni/omni/omni_v0.h

Solution: Add support for planner hook with test included.
I merged my fork with the latest and realized the PR needs to go to `next/omni` branch. Figured a better git workflow. Hence, closing the previous PR https://github.com/omnigres/omnigres/pull/527.

Problem: Omni doesn't have support for planner hook

---

extensions/omni_vfs/local_fs.c
extensions/omni_vfs/tests/deleted.yml
extensions/omni_vfs/tests/local_fs.yml

When local_fs information is deleted from `local_fs_mounts`, omni_vfs would crash. This is not great!
Solution: ensure it checks if there's at least one record and error out otherwise.
Most likely, the original code was built on assumption that there's always going to be a value available in this table because it will always be preceded by `omni_vfs.local_fs()` function call. But that's actually not true.
Kudos to @rmodpur for spotting this.

Problem: deleted omni_vfs local_fs mount

---

extensions/omni_sql/CHANGELOG.md

This makes it harder to track where 0.2.1 arrived.
Solution: add the link to the changelog

Problem: missing version PR link in omni_sql changelog

---

extensions/omni/CHANGELOG.md
extensions/omni/omni.c
extensions/omni/test/tests/tests.yml

Solution: make sure path key always has trailing zeroes for the hash function to return the same result.
Multiple loading happened because in some cases the trailing data past NUL was arbitrary but the hash table always hashes keys up to PATH_MAX.

Problem: omni module might get loaded more than once

---

extensions/omni/CHANGELOG.md
extensions/omni/omni.c

Solution: ensure to use a key that is hashed stably
Similarly to d84378ee08f75f77b0760117145c9cfbbbe1b974, we may be using an unstably hashed key.

Problem: sometimes omni module may not get unloaded

---

extensions/omni_httpd/docs/install.md
extensions/omni_httpd/mkdocs.yml

New users run into a case where they install omni_httpd but it doesn't work.
Solution: provide documentation on install omni as well
In the future, this should be better addressed by omni_httpd warning the user of the corrective action to be taken.
Better yet, need to continue thinking about simpler installation procedures for such. Can we ship a version of `omni` with all omni extensions?

Problem: it's unclear how to install omni_httpd

---

Dockerfile

```
error: failed to compile `cargo-pgrx v0.11.4`, intermediate artifacts can be found at `/tmp/cargo-installpit9R4`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
package `clap v4.5.4` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.0
```
Solution: pin `cargo-pgrx` version to one that works on Rust 1.72
https://github.com/tcdi/plrust/issues/410
Upgrade plrust to 1.2.8 while at it.

Problem: building docker images fails

---

extensions/omni_httpc/CHANGELOG.md
extensions/omni_httpc/tests/redirect.yml

Solution: ensure it's clearing the reconfiguration correctly
This is not perfect, as it is obscure and undocumented knowledge, but this is how it works right now.
The installation of extensions generates two configuration changes, and we need to clear those before we can ensure the last useful configuration change is made before we test it.

Problem: sporadic failure of redirect test in omni_httpc

---

extensions/omni_sql/CHANGELOG.md
extensions/omni_sql/lib.c
extensions/omni_sql/tests/omni_sql/post_parse_analyze_hook.yml

This happens with `pg_stat_statements` is loaded:
```
TRAP: failed Assert("len_to_wrt >= 0"), File: "pg_stat_statements.c", Line: 2708, PID: 15393
0   postgres                            0x0000000100f370f4 ExceptionalCondition + 236
1   pg_stat_statements.dylib            0x0000000101532234 generate_normalized_query + 328
2   pg_stat_statements.dylib            0x0000000101531950 pgss_store + 440
3   pg_stat_statements.dylib            0x000000010152db18 pgss_post_parse_analyze + 484
4   postgres                            0x0000000100829fa4 parse_analyze_fixedparams + 256
5   omni_httpd--0.1.2.so                0x000000010bda22d4 omni_sql_is_valid + 408
6   omni_httpd--0.1.2.so                0x000000010bc6d884 handlers_query_validity_trigger + 512
7   postgres …
```

Problem: segfault during omni_httpd.handlers update

---

extensions/omni/CHANGELOG.md
extensions/omni/init.c
extensions/omni/omni.c
extensions/omni/omni_common.h
omni/omni/omni_v0.h

Most of the time, extensions compiled for one minor version should work on another, but that's not universally true. There are some changes between different minor versions that may make the extensions behave incorrectly or (potentially) cause an abnormality.
Solution: make `omni` module loader issue warnings when it encounters extensions compiled for a different version of Postgres.
There's an important implication of this change: we need to change how we ship the builds of our extensions. We should probably run tests against all minor revisions, too.

Problem: differences between minor Postgres versions

---

README.md
cmake/PostgreSQLExtension.cmake

For example, in a a new environment, `make psql_omni_httpd` won't bring other extensions, requiring `make psql_omni_other_ext`.
Solution: prepare all extensions when using one
This is a bit slower, so now `make -j psql_EXT` is recommended.

Problem: using other extensions in `make psql_EXT`

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/docs/intro.md
extensions/omni_httpd/master_worker.c
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/tests/limited_max_workers.yml

omni_httpd master and its workers loop infinitely when postgres `max_worker_processes` is 8 (the default).
This happens because:
- `omni_httpd.http_workers` defaults to the number of cores (16 in this case).
- The `RegisterDynamicBackgroundWorker` call fails because there are no background worker slots available (limited by `max_worker_processes`).
- The httpd master gets stuck busy-waiting for all workers to start their loops [1].
- The workers get stuck retrying the EAGAIN result of their socket [2].
Solution: handle the failed `RegisterDynamicBackgroundWorker` result.
This function returns false when the background worker can't start.
[1]: https://github.com/omnigres/omnigres/blob/9c2bcc6c9aa804a6b7e209a02d218449342aa1a7/extensions/omni_httpd/master_worker.c#L523
[2]: …

Problem: omni_httpd looping infinitely

---

cmake/FindH2O.cmake

Using DISABLE_LIBUV as done on `cmake/FindH2O.cmake`:
```
list(APPEND _h2o_options "DISABLE_LIBUV ON")
```
Will not produce the libh2o library according to:
- https://github.com/h2o/h2o/blob/16b13eee8ad7895b4fe3fcbcabee53bd52782562/CMakeLists.txt#L728-L730
- https://github.com/h2o/h2o/blob/16b13eee8ad7895b4fe3fcbcabee53bd52782562/CMakeLists.txt#L814-L816
Solution: remove the libh2o TARGET

Problem: cmake TARGET libh2o is unused

---

extensions/omni/CHANGELOG.md
extensions/omni/extension.c
extensions/omni/hook_harness.c
extensions/omni/init.c
extensions/omni/omni.c
extensions/omni/omni_common.h
extensions/omni/test/CMakeLists.txt
extensions/omni/test/no_fun.c
extensions/omni/test/tests/no_fun/test.yml

We detect extensions through references of C-language functions in `pg_proc`.
This generally works for extensions that expose some functions, but doesn't work for those that just do some work on initialization (background worker startup, etc.)
Solution: switch to `pg_extension` to detect extensions directly
One potential downside of this approach is that we won't support extensions with more than one shared object.

Problem: using `pg_proc` to detect extensions

---

Dockerfile

We already use 16.4 in our build system
Solution: keep it up to date

Problem: Dockerfile still referencing 16.3

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/event_loop.c
extensions/omni_httpd/http_worker.c

Simple observation under load proves that, and further exploration showed (on macOS, using `leaks` tool) a 96-byte leak on every request.
Solution: ensure request message structures are always freed (and their mutexes destroyed)
Current architecture is a little bit complicated, and it shows. The crux of the problem was that `request_message_t` messages are allocated using `malloc` but they were never really freed upon proper finalization of the request. We did track request deallocation but only to null it out in the message to signal that the request is gone. We are now freeing the message too, if the request has completed.
We did not attach the message to the request's pool because that would be a circular dependency (it would be gone if the request is gone)

Problem: omni_httpd leaks memory on every request

---

.github/workflows/build.yml
.github/workflows/debug.yml
.github/workflows/ext-scripts.yml

See the announcement:
https://flyci.net/blohttpsg/flyci-discontinue-macos-runners
Solution: switch to WarpBuild's runners

Problem: FlyCI macOS runners shutting down next month

---

extensions/omni_httpd/http_worker.c

They are an artifact of an earlier implementation method for security restrictions.
Solution: remove them

Problem: unused user variables in omni_httpd

---

extensions/omni_sql/CHANGELOG.md
extensions/omni_sql/lib.c
extensions/omni_sql/src/execute.sql
extensions/omni_sql/tests/omni_sql/execute.yml
extensions/omni_sql/tests/omni_sql/is_returning_statement.yml

For example:
```
select omni_sql.execute('select 1; select 2');
execute
-------------
{"rows": 1}
```
Solution: ensure `execute` _actually_ iterates over statements
While at it, add support for multiple statements to `is_returning_statement` for completeness.

Problem: omni_sql.execute returns wrong results on multiple statements

---

extensions/omni_httpd/http_worker.c
extensions/omni_httpd/tests/sql_handler.yml

If this function is defined as a SQL function, it will fail with the violation of assertion for presence of an active snapshot, as they require these.
Solution: ensure we always have a snapshot to operate in
This requires a kludge for non-atomic functions implemented in languages like PL/pgSQL if they use SPI. SPI tries to check if portals account for all active snapshots. But having no portal, they don't, resulting in this failure:
```
portal snapshots (0) did not account for all active snapshots (1)
```

Problem: calling SQL-language omni_httpd.handler

---

cmake/FindPostgreSQL.cmake

Having this problem:
```
Undefined symbols for architecture arm64:
"_AllocSetContextCreateInternal", referenced from:
_switch_to_new in libpgaug_test.c.o
_switch_back_to_old in libpgaug_test.c.o
_switch_back_to_old_with_return_ in libpgaug_test.c.o
_switch_when_finalizing in libpgaug_test.c.o
```
Solution: ensure to always use configured or supplied Postgres
Apparently, on macOS, cmake's find_program could pick up things like `/Applications/postgres.app/Contents/MacOS/Postgres` even when `CMAKE_FIND_APPBUNDLE` is set to `NEVER` :shrug:
So, construct the path to `postgres` manually instead.

Problem: failing to build Omnigres on macOS

---

extensions/omni_var/CHANGELOG.md
extensions/omni_var/omni_var.c
extensions/omni_var/tests/session_variables.yml
extensions/omni_var/tests/txn_variables.yml

Behavior of setting and retrieving variables of types like `uuid` is undefined: segfault, error, garbage, and normal.
Solution: ensure we handle fixed-size values correctly

Problem: fixed size type handling on omni_var (🚀 omni_var 0.2.1)

---

extensions/omni_web/CHANGELOG.md
extensions/omni_web/migrate/6_cookie_get.sql
extensions/omni_web/src/cookie_get.sql
extensions/omni_web/tests/cookies.yml

Listing all cookies is useful, and we can filter them, but often times we just need to get one cookie by name.
Solution: designate a function for that

Problem: `cookies` function does too much

---

extensions/omni_id/CHANGELOG.md
extensions/omni_id/docs/identity_type.md
extensions/omni_id/src/identity_type.sql
extensions/omni_id/tests/id.yml

Some use UUIDs for identifiers. They can be useful to obscure the volumes of records.
Solution: add support for UUID base type

Problem: omni_id is limited to integers

---

extensions/omni_id/CHANGELOG.md
extensions/omni_id/CMakeLists.txt
extensions/omni_id/docs/uuidv7.md
extensions/omni_id/migrate/2_uuidv7.sql
extensions/omni_id/tests/id.yml
extensions/omni_id/tests/uuidv7.yml
extensions/omni_id/uuidv7.c

This makes it less acceptable as an identity / primary key as it may result in poor locality.
Solution: port current patch for UUIDv7 from Postgres CF
https://www.postgresql.org/message-id/flat/CAAhFRxitJv=yoGnXUgeLB_O+M7J2BJAmb5jqAT9gZ3bij3uLDA@mail.gmail.com
As long as it is okay to expose the time of the key creation, UUIDv7 is a great option for an UUID-based key.
See also:
https://buildkite.com/blog/goodbye-integers-hello-uuids
<blockquote>
With this change (along with several other changes over a 6 week period), we observed a 50% reduction in the WAL (Write Ahead Log) rate of the primary database. A similar reduction in write IO was also observed. This reduction in the WAL rate allowed the team to easily set up read replicas and perform other database migration tasks. </blockquote> …

Problem: uuidv4 is not monotonic

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/event_loop.c

This is because it uses `h2o_mem_alloc_pool` API incorrectly there.
Solution: use it correctly
Supply the type, not the size

Problem: omni_httpd underallocated memory for proxying

---

README.md
extensions/omni_polyfill/CHANGELOG.md
extensions/omni_polyfill/CMakeLists.txt
extensions/omni_polyfill/README.md
extensions/omni_polyfill/arrays.c
extensions/omni_polyfill/docs/polyfills.md
extensions/omni_polyfill/migrate/1_arrays.sql
extensions/omni_polyfill/mkdocs.yml
extensions/omni_polyfill/omni_polyfill.c
extensions/omni_polyfill/tests/arrays.yml
versions.txt

This time it is `trim_array` (available on Postgres 14+), but we're still supporting Postgres 13.
Solution: copy `trim_array` into the new `omni_polyfill` extension

Problem: some functionality is not available on older Postgres (🚀 omni_polyfill 0.1.0)

---

extensions/omni_types/CHANGELOG.md
extensions/omni_types/migrate/3_sum_type_extconfig.sql

Solution: include `omni_types.sum_types` table into extconfig

Problem: sum types will not be included into pg_dump

---

extensions/omni_seq/CHANGELOG.md
extensions/omni_seq/id.h

In particular, compiling on Ubuntu Noble LTS against PGDG PostgreSQL 16 is failing with an error (not being able to find a header file)
Solution: adjust referenced header location
FindPostgreSQL cmake file already includes both client & server include directories. All we have to do is include the header we want without being specific about the path. This works with both RedHat and on Ubuntu PGDG packages. Server headers are a separate package on Ubuntu.

Problem: failing to compile omni_seq in some cases

---

cmake/FindH2O.cmake
cmake/FindWSLAY.cmake
extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/event_loop.c
extensions/omni_httpd/event_loop.h
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/http_worker.h
extensions/omni_httpd/migrate/8_websocket.sql
extensions/omni_httpd/omni_httpd.c

This is a major problem for anything remotely interesting these days.
Solution: devise the first version of WebSocket handling
Current approach definitely has deficiencies. For example, using UNIX domain sockets can be problematic here. It's good that sending a message to UNIX domain socket is directly connecting us with the consumer (the networking thread) thus ensuring that we are not simply buffering the messages. But if, for some reason, the consumer is not reading, it'll block us.
An even bigger problem is that we currently won't try to send messages to any other worker and will simply schedule messages for the current buffer. It's okay for the initial prototype, but won't scale well.

Problem: omni_httpd does not support WebSockets

---

extensions/omni_id/CHANGELOG.md
extensions/omni_id/src/identity_type.sql
extensions/omni_id/tests/id.yml

Solution: make them `strict` as their underlying implementations require

Problem: identity types crash on null values

---

extensions/omni_id/CHANGELOG.md
extensions/omni_id/src/identity_type.sql

Or so do the signatures say! This prevents parallelization optimizations.
Solution: mark them `parallel safe` as their underlying functions

Problem: identity type functions are not parallel safe

---

extensions/omni/CHANGELOG.md
extensions/omni/init.c
extensions/omni/test/migrate/1.sql
extensions/omni/test/omni_test.c
extensions/omni/test/tests/tests.yml
omni/omni/omni_v0.h

This is problematic for some extensions because they can't detect whether omni has been preloaded in `_PG_init`, causing them to be loaded successfully even though they may not be actually operational.
This may shift the need to check whether `_Omni_init` has been called in exported functions, which is adding checks for every invocation and is error-prone (it is easy to forget to do so)
Solution: establish a "marker" that omni is loaded
This is done through a rendezvous variable. Relatively low-key way to do so and it can be then checked in extension's `_PG_init` and if omni is required for operations, it can error out.

Problem: impossible to establish presence of omni

---

extensions/omni/test/tests/upgrade_extra_deps.yml
extensions/omni_types/CHANGELOG.md
extensions/omni_types/CMakeLists.txt
extensions/omni_types/README.md
extensions/omni_types/docs/function_signature_types.md
extensions/omni_types/funsig_type.c
extensions/omni_types/migrate/3_function_signature_type.sql
extensions/omni_types/src/function_signature_type.sql
extensions/omni_types/src/function_signature_type_of.sql
extensions/omni_types/tests/function_signature_type.yml

Sure, they denote that an OID is a function/procedure, and, in case of `regprocedure`, that function has certain arguments.
But the type itself does not convey the signature, which makes it not possible for us to call these function.
Solution: design "function signature types"
This type is also an OID but we also store information about its full signature and we validate on casts that the functions match the entire signature.
These makes these types represent the actual function signature, making them callable. One can compose them into interfaces through composite types.
---
Missing:

Problem: `regproc[edure]` have limited usefulness

---

.gitignore
pkgs/mkpkgs
pkgs/mkrpms
pkgs/rocky.dockerfile

This commit adds the ability to easily produce RPMs for Omnigres on any capable machine with Docker installed. Please review the ./pkgs/mkpkgs script for notes on setup. Then just call ./pkgs/mkpkgs at the command line. If you only want one archiecture then call `ARCH=linux/arm64 ./pkgs/mkpkgs`.
Please provide as much criticism as you like. I'll fixup commits and rebase.
The build machine setup for this has been exercising this script. Try it yourself if you like.

Add a script and a dockerfile to build RPM pkgs for amd64 & arm64

---

extensions/omni_auth/CHANGELOG.md
extensions/omni_auth/CMakeLists.txt
extensions/omni_auth/README.md
extensions/omni_auth/docs/basics.md
extensions/omni_auth/docs/password.md
extensions/omni_auth/migrate/1_basics.sql
extensions/omni_auth/migrate/2_password.sql
extensions/omni_auth/mkdocs.yml
extensions/omni_auth/src/authenticate_password.sql
extensions/omni_auth/src/hash_password.sql
extensions/omni_auth/src/hashing_algorithm.sql
extensions/omni_auth/src/password_work_factor_timings.sql
extensions/omni_auth/src/set_password.sql
extensions/omni_auth/src/successful_authentification_password_authentication_attempts.sql
extensions/omni_auth/src/work_factor.sql
extensions/omni_auth/tests/passwords.yaml
extensions/omni_auth/tests/set_password.yaml
versions.txt

While not a problem in itself, the fact that every application has to do it, leads to regular reinvention of the wheel.
Solution: design omni_auth to be a common building block
At the first go, it only supports password-based authentication and only supports bcrypt for hashing. More methods and hashing algorithms are to be added later.

Problem: authenticating users (🚀 omni_auth 0.1.0)

---

extensions/omni_aws/CHANGELOG.md
extensions/omni_aws/src/s3_presigned_url.sql
extensions/omni_aws/tests/minio.yml
versions.txt

This requires the file to be uploaded to the backend (Omnigres) and then sent to S3. This introduces an unnecessary step and potential failures (and handling them)
Solution: provide support for pre-signing upload URLs

Problem: uploading files to S3 from the browser (🚀 omni_aws 0.1.1)

---

pg_yregress/CHANGELOG.md
pg_yregress/test.c
pg_yregress/test.yml

When no notices are received from the server, it looks like as if all notices expected were received, which is clearly incorrect.
Solution: ensure we always compare notices

Problem: pg_yregress ignores `notices` key

---

cmake/FindPostgreSQL.cmake

Stops at cmake script not being able to copy Postgres' sharedir.
Solution: when we patch pg_config_paths.h, ensure to reuse old value
Otherwise we made an assumption that doesn't always hold.

Problem: failing to build Omnigres on some sysems

---

extensions/omni/CHANGELOG.md
extensions/omni/extension.c
extensions/omni/omni.c
versions.txt

Error message: "unsupported byval length"
Solution: don't try to pre-cache `TupleDesc`
(it's readily available in `Relation` anyway)

Problem: omni may fail to initialize a module (🚀 omni 0.2.1)

---

.github/workflows/build.yml
.github/workflows/docker.yml

Solution: pin runner image to Ubuntu 22.04
Eventually, we need to upgrade, but for now, we need them to work.

Problem: CI jobs started to fail

---

cmake/PostgreSQLExtension.cmake

While we don't include them into `package_extensions` we still produce individual targets that may be picked up by other scripts. We don't want that
Solution: do not create individual packaging targets for such extensions

Problem: packaging private extensions

---

extensions/omni_sql/CHANGELOG.md
extensions/omni_sql/omni_sql.c
extensions/omni_sql/tests/omni_sql/execute.yml

When we pass parameters in a JSON array that are typed as text but specify the type as something other than text (or physical equivalent of it), the resulting data is effectively garbage.
Solution: ensure we call input function on the given string

Problem: omni_sql.execute doesn't work well with custom types

---

.github/workflows/ext-scripts.yml
cmake/FindPostgreSQL.cmake

We have new versions of Postgres that fix non-impossible-to-reproduce bugs (one such bug is a [race condition in serializable transactions](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=234f6d09e))
Solution: use newer releases by default

Problem: using older versions of Postgres

---

Dockerfile

17.1 was quickly superseded by 17.2 because of regressions.
Solution: use 17.2 now that it is available

Problem: Dockerfile still uses 17.1

---

extensions/omni/CHANGELOG.md
extensions/omni/omni.c
extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/CMakeLists.txt
extensions/omni_httpd/master_worker.c
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/omni_httpd.h
extensions/omni_httpd/tests/multi_db.yml
omni/omni/omni_v0.h
versions.txt

If the extension is installed in more than one database, only one database will have it running.
Solution: ensure omni_httpd tracking is database-scoped
This also transfered the atomic switchboard to omni_httpd itself (posing a good question: should we remove this functionality from the `omni` interface?)
Another concern here is that using multiple databases leads to a much higher number of workers used. We use the same number of workers per database. How should we handle this in the future, split the number between databases? Introduce a total cap and a parameter for per-database workers?
omni now zero-initializes shmem allocations. This is a safe change but may potentially be a performance issue, though unlikely. If that will ever be needed, we can introduce a flagged version of the …

Problem: omni_httpd doesn't work on multiple databases (🚀 omni_httpd 0.2.3, omni 0.2.2)

---

.github/workflows/docker.yml
Dockerfile
docker/initdb-omnikube/001-settings.sql.templ
docker/initdb-omnikube/002-restart.sh.templ
docker/initdb-omnikube/003-default-extensions.sql.templ
docker/initdb-omnikube/004-default-search_path.sql.templ
extensions/omni_httpc/CHANGELOG.md
extensions/omni_httpc/docs/reference.md
extensions/omni_httpc/migrate/3_http_execute.sql
extensions/omni_httpc/migrate/5_add_http_execute_cert_options.sql
extensions/omni_httpc/omni_httpc.c
extensions/omni_httpc/src/http_execute_options.sql
extensions/omni_httpc/src/http_execute_options_prev.sql
extensions/omni_kube/CMakeLists.txt
extensions/omni_kube/README.md
extensions/omni_kube/docs/api.md
extensions/omni_kube/docs/views.md
extensions/omni_kube/migrate/1_api.sql
extensions/omni_kube/migrate/1_pod_credentials.sql
extensions/omni_kube/migrate/2_views.sql
extensions/omni_kube/mkdocs.yml
extensions/omni_kube/src/api.sql
extensions/omni_kube/src/pod_credentials.sql
versions.txt

Omnigres is often portrayed as an advanced application runtime – the one that embraces data-centric design and control flow.
But if it is an application runtime, how does it fare with today's methods of deployment? Does it integrate well?
Solution: propose a lightweight integration with Kubernetes
omni_kube allows easily making Kubernetes API calls so that one can orchestrate resources and get views into what's happening.
This change also required me to add some CA certificate-related functionality to omni_httpc.
---

Problem: integration with the rest of the world (🚀 omni_kube 0.1.0, omni_httpc 0.1.3)

---

extensions/omni_sql/CHANGELOG.md
extensions/omni_sql/omni_sql.c
extensions/omni_sql/tests/omni_sql/execute.yml

Fails with `cache lookup failed for type`
Solution: assume `null`s to be strings at first
This gives us an opportunity to cast it.

Problem: omni_sql.execute with nulls for typeless parameters

---

extensions/omni_polyfill/docs/polyfills.md

It puts `omni_polyfill` and `pg_catalog` in the begining which affects the selection of the schema to create objects in. We don't want that to be affected.
Solution: put them in the end

Problem: omni_polyfill installation instruction

---

cmake/PostgreSQLExtension.cmake
extensions/omni_aws/CMakeLists.txt
extensions/omni_json/CHANGELOG.md
extensions/omni_json/CMakeLists.txt
versions.txt

This is because all of our extensions are built as `superuser=true` (default) by default, requiring superuser, even when this is not necessary.
Solution: allow regulating this parameter through CMake

Problem: extensions can't be installed by non-superuser (🚀 omni_aws 0.1.2, omni_json 0.1.1)

---

README.md
extensions/omni_credentials/CHANGELOG.md
extensions/omni_credentials/CMakeLists.txt
extensions/omni_credentials/README.md
extensions/omni_credentials/docs/credentials.md
extensions/omni_credentials/migrate/1_instantiate.sql
extensions/omni_credentials/mkdocs.yml
extensions/omni_credentials/src/instantiate.sql
extensions/omni_credentials/src/instantiate_file_store.sql
extensions/omni_credentials/tests/credentials.yaml
extensions/omni_credentials/tests/credentials_file_store.yaml
versions.txt

There's no standard facility provided by Omnigres, and this is very common functionality.
Solution: add omni_credentials
It's a template extension that can be instantiated independently of the extension itself (though by default, it instantiates itself)
It employs a neat trick useful in dev mode: you can instantiate a file store that will be kept in sync with a file on the filesystem. In the future, this can also potentially use omni_vfs (once https://github.com/omnigres/omnigres/pull/710 is in).
This means that while developing, you can keep encrypted credentials file up to date.

Problem: managing API keys and other secrets (🚀 omni_credentials 0.1.0)

---

.github/workflows/docker.yml
README.md
docs/quick_start.md
extensions/omni_python/docs/intro.md

(Which is currently 17.2)
However, this can be problematic when one needs a specific major version for one reason or another (for example, some extensions do not always support the latest version)
Solution: build image per major version

Problem: docker image is only built for latest Postgres

---

Dockerfile
docker/apt-pin

Example:
```
The following packages have unmet dependencies:
postgresql-16-pgdg-pgroonga : Conflicts: postgresql-16-pgroonga but 3.2.5-1PIGSTY~bookworm is to be installed
```
Solution: make Pigsty higher priority and exclude pgpg-denominated packages and dbgsym in a search to avoid conflicts

Problem: container image build started failing

---

Dockerfile
extensions/omni_python/CHANGELOG.md
extensions/omni_python/CMakeLists.txt
extensions/omni_python/migrate/5_install_requirements.sql
extensions/omni_python/migrate/6_wheel_path.sql
extensions/omni_python/omni_python.c
extensions/omni_python/src/install_requirements.py

It's very inconvenient that for every deployment, we need to provision `find_links` configuration.
Solution: make omni_python expect packaging to put them into pkglibdir
More specifically, `pkglibdir/omni_python--VERSION` directory.

Problem: where should Python wheels come from?

---

extensions/omni_python/CHANGELOG.md
extensions/omni_python/src/execute.sql
extensions/omni_python/src/functions.py

If we try to load a module and it wasn't available, and then install it and try again, omni_python might not see it.
Solution: invalidate loader caches
It is not very efficient to put this into every function call, but this is currently handling the fact that installation may occur in a different backend and therefore invalidating there wouldn't do anything.
While at it, let's make sure we don't add new `sys.path` if it is already there.

Problem: importing a Python module after a failed attempt

---

Dockerfile

Conflicts between `timescaledb` and `timescaledb-tsl` as well as `pg-anon` and `anonymizer`
Solution: hard-code resolution of this conflict
Once we switch over to pgpm, this should not be a problem because because we'll (hopefully) rely on a single source.

Problem: container images build failure

---

README.md
extensions/omni_service/CHANGELOG.md
extensions/omni_service/CMakeLists.txt
extensions/omni_service/README.md
extensions/omni_service/docs/management.md
extensions/omni_service/docs/service_integration.md
extensions/omni_service/migrate/1_service.sql
extensions/omni_service/mkdocs.yml
extensions/omni_service/src/instantiate.sql
extensions/omni_service/src/register_service.sql
extensions/omni_service/src/service_provisioning_trigger.sql
extensions/omni_service/src/service_start.sql
extensions/omni_service/src/service_stop.sql
versions.txt

Every service may have its own API when it comes to their operations. This makes creation of generalized tooling difficult.
Solution: create a uniform service control plane
---

Problem: managing different services (🚀 omni_service 0.1.0)

---

.github/workflows/build.yml

More info at https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Solution: Use actions/upload-artifact@v4
cherry-picked from @diogob's work

Problem: Build was breaking due to deprecated action

---

extensions/omni_vfs/CHANGELOG.md
extensions/omni_vfs/CMakeLists.txt
extensions/omni_vfs/docs/reference.md
extensions/omni_vfs/migrate/6_remote_fs.sql
extensions/omni_vfs/migrate/remote_fs_checks.sql
extensions/omni_vfs/src/remote_fs.sql
extensions/omni_vfs/src/remote_fs_file_info.sql
extensions/omni_vfs/src/remote_fs_list.sql
extensions/omni_vfs/src/remote_fs_read.sql
extensions/omni_vfs/src/remote_fs_write.sql
extensions/omni_vfs/tests/local_fs.yml
extensions/omni_vfs/tests/remote_fs.yml

We have a case where we have to copy files from one filesystem to another (table_fs) in a different database just so that database can use the files.
However, that puts a lot of burden onto those who implement it. See `omni_schema.assemble_schema` for an example of that.
Solution: allow for remote file system access
As long as you can access a database over dblink, simply proxy calls to that other database. Let's call it a "remote filesystem"
The design may not yet be ideal. I am in particular not 100% happy with the idea of the "constructor" that we pass as a string to be able to indicate a filesystem remotely. It's probably not the most terrible thing, but it irks me as any text being passed to the other side. But that's dblink for you – it does that anyway. The crux of this problem is …

Problem: deploying files from a filesystem in a different database

---

README.md
cmake/PostgreSQLExtension.cmake

Doing this manually with `cp` is not fun, but that's the only option we have right now, after `package_extensions` is done.
Solution: introduce `install_extensions` and `install_EXT_extension` targets
These will copy extensions into Postgres' designated directories.

Problem: installing extensions into Postgres

---

Dockerfile

If/when Omnigres gets published on Pigsty, that'll come into a conflict with the freshest build of our image.
Solution: don't get Omnigres from Pigsty in our image

Problem: potential conflict with Omnigres from Pigsty

---

misc/inja/inja.cpp

The ends_with is introduced by C++20, which is not available by default in distro like EL8
Solution: replace the function with a bespoke version to work around it

Problem: inja renderer uses C++ 20's ends_with

---

Dockerfile

This is because mooncake and duckdb conflict over libduckdb.so
Solution: choose one (mooncake)

Problem: container image build fails

---

README.md
extensions/omni_cloudevents/CHANGELOG.md
extensions/omni_cloudevents/CMakeLists.txt
extensions/omni_cloudevents/README.md
extensions/omni_cloudevents/docs/cloud_events.md
extensions/omni_cloudevents/migrate/1_instantiate.sql
extensions/omni_cloudevents/mkdocs.yml
extensions/omni_cloudevents/src/instantiate.sql
extensions/omni_cloudevents/tests/test.yaml
versions.txt

Or, rather, the lack of universality. How do we know what kind of event is this event?
Solition: add initial support for CloudEvents
It's simple and its getting some support and use throughout the industry.
At this point, this is a proof-of-concept that allows for basic publishing of events, with publishers such as "NOTICE publisher" handling their delivery.

Problem: event messaging between different systems (🚀 omni_cloudevents 0.1.0)

---

extensions/omni_python/CHANGELOG.md
extensions/omni_python/migrate/7_packages.sql
extensions/omni_python/src/installed_packages.py
extensions/omni_python/tests/omni_python.yml

This becomes problematic when we introspect into the database to see what needs to be installed, especially during migrations.
Solution: expose `omni_python.installed_package`
This will also allow us to track changes if we snapshot it.

Problem: unable to see which Python packages are installed

---

extensions/omni_python/CHANGELOG.md
extensions/omni_python/src/install_requirements.py

It's only printed on the stdout, and so remotely connected clients don't see anything, and it might take time to install packages.
Solution: make it visible by redirecting output to notices
This is still not perfect, but it's a good start!

Problem: omni_python package installation is virtually invisible

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/http_worker.c

This may present a timing problem when we want to query recently modified data based on the fact that the response has already been sent.
We've observed this in sporadic test failures.
Solution: ensure we commit first
This is not yet perfect case coverage as this doesn't include WebSocket sending as it will send messages eager before transanction is committed.
This generally raises a good question: should we apply the same transactional guarantees to outbound WebSocket messages? Should we provide an option for this, defaulting to either choice?

Problem: sending HTTP response before committing the transaction

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/http_status_reasons.h
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/tests/http.yml

This looks a bit weird:
```
HTTP/1.1 403 OK
```
Solution: lookup correct status reason in a dictionary

Problem: HTTP responses always use OK as the reason

---

extensions/omni_web/urlpattern.cpp

There is a conflict between gettext imported from libintl for ada_url and the gettext defined in c.h in PostgreSQL's headers.
The relevant part of the error:
```
/usr/include/libintl.h:39:14: error: expected unqualified-id before ‘const’
39 | extern char *gettext (const char *__msgid)
|              ^~~~~~~
...
gmake[2]: *** [extensions/omni_web/CMakeFiles/omni_web.dir/build.make:121: extensions/omni_web/CMakeFiles/omni_web.dir/urlpattern.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:6951: extensions/omni_web/CMakeFiles/omni_web.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```
Solution: Move the PostgreSQL headers to after the ada headers into the extern C block.

Problem: A build from scratch on a Debian system errors when compiling omni_web

---

extensions/omni_schema/src/meta/catalog.sql
extensions/omni_schema/src/meta/identifiers.sql
extensions/omni_schema/tests/meta_role.yml
extensions/omni_schema/tests/meta_role_can_login.yml
extensions/omni_schema/tests/meta_role_connection_limit.yml
extensions/omni_schema/tests/meta_role_create_db.yml
extensions/omni_schema/tests/meta_role_create_role.yml
extensions/omni_schema/tests/meta_role_inherit.yml
extensions/omni_schema/tests/meta_role_replication.yml
extensions/omni_schema/tests/meta_role_setting.yml
extensions/omni_schema/tests/meta_role_superuser.yml
extensions/omni_schema/tests/meta_role_valid_until.yml

The view omni_schema.role is not in 6NF making a diff between rows harder.
Normalize it.
Note that there is a special case for the `role_setting` view.
Since each array item in `pg_db_role_setting.setconfig` is added or removed by a distinct `ALTER ROLE` command I created one line in `role_setting` for each config key.

The view omni_schema.role is not in 6NF 

---

.github/workflows/build.yml
.github/workflows/docker.yml
cmake/FindPostgreSQL.cmake

We keep running into its limitations. It stops being supported in Nov 2025, so in about 9 months.
Solution: drop supporting it now
This will redirect energy required to support it to something more useful.
Note that this doesn't change some of the syntax or conditional compilation that pertains to Postgres 13. We just stop building and testing on it. Soon enough, some extensions will stop working on it.

Problem: Postgres 13 is too old

---

Dockerfile
docker/initdb-slim/005-http-handler.sql.templ
extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/docs/static_file.md
extensions/omni_httpd/migrate/12_handlers.sql
extensions/omni_httpd/src/instantiate_static_file_handler.sql
extensions/omni_httpd/src/static_file_handler.sql
extensions/omni_httpd/tests/static_file.yml

We have an older version of the static file handler, however, it is designed for the soon-to-be-removed cascading query API.
Solution: implement a handler for the new routing API
As an example, we include /docs browser in the container image.

Problem: serving static files using omni_httpd

---

extensions/omni_types/CHANGELOG.md
extensions/omni_types/sum_type.c

We keep looking up the variant and the variant comparison functions a lot.
Solution: cache these
Bound to a xmin, we keep a cache of what we know about the types. This is still
imperfect because we don't preserve the cache across the xmin boundary where we
could have. For that, we would to need to implement a relcache handler in
omni_types to refresh the cache whenever the underlying table changes.
Also, the cache is only used in variant lookup but not in in/out functions.

Problem: sum type equality comparison is slow

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/tests/websocket.yml

If `omni_httpd.websocket_handler()` returns false, no HTTP response is sent. And it seems like the worker just hangs for some reason -- it never responds to future requests -- even if the connection is closed by the peer.
However, if the handler returns null, it does send an HTTP response that does not upgrade the connection to a WebSocket.
But the comment for the handler indicates that any non-true value should be treated the same:
If it returns anything but true, the connection is rejected.
Solution: send a response in any case
This change should send an HTTP even if false is returned and only upgrade if the handler returns true.
I'm still not sure why the worker seemed to not receive further requests when it failed to send a response here. (Though omni_httpd.stop and start would …

Problem: no response from false websocket_handler

---

extensions/omni/CHANGELOG.md
extensions/omni/hook_harness.c
extensions/omni/omni_common.h

In [525392d](https://github.com/postgres/postgres/commit/525392d5727f469e9a5882e1d728917a4be56147), ExecutorStart_hook has changed its signature and `omni` no longer compiles on master.
Solution: accommodate the change
We'll return valid being true for prior versions.

Problem: recent change to executor start hook

---

extensions/omni/CHANGELOG.md
extensions/omni/omni.c
versions.txt

Solution: update internal flag values
[cd3ccf88aacb43b7232d6834dc886ff8538c6ce8](https://github.com/postgres/postgres/commit/cd3ccf88aacb43b7232d6834dc886ff8538c6ce8) changed these and tests started failing.

Problem: omni fails to build on master Postgres (🚀 omni 0.2.7)

---

extensions/omni_credentials/CHANGELOG.md
extensions/omni_credentials/docs/credentials.md
extensions/omni_credentials/src/instantiate.sql
extensions/omni_credentials/src/instantiate_file_store.sql
extensions/omni_credentials/tests/credentials.yaml
extensions/omni_credentials/tests/credentials_file_store.yaml

When we want to use them across different subsystems and extensions, they lack specificity. It's just an encrypted key/value store.
It's not clear what naming convention should be used, for example.
Solution: expand the concept to include further metadata
"What kind of credential?" – `kind`
"Who can have access to it?" – `principal`
"What is the scope of the credential?" – `scope`
This will allow much better "notation". Since we're getting all these details, it now makes sense to enable RLS on this table and by default, filter by principal. Users can add more policies to it. The reason why this metadata is not factored out is so that RLS _can_ be used there without sub-queries.

Problem: generializing omni_credentials

---

pg_yregress/test.yml

One of the values returned by master Postgres has changed
Solution: unify testing to avoid the divergence

Problem: pg_yregress test on master fails

---

Dockerfile

Solution: Install the package libc++1-19 which provides the required
library in our slim image.

Problem: The current docker image cannot load omni_httpd extension since it requires libc++ which is not present there.

---

extensions/omni_vfs/CHANGELOG.md
extensions/omni_vfs/src/file_info_table_fs.sql
extensions/omni_vfs/tests/local_fs.yml
extensions/omni_vfs/tests/table_fs.yml

/claim #796 
Problem takes place because the file_info function was using an inner join with table_fs_file_data.
Since directories don't have entries in this table, the query returned no results (all null values) when attempting to retrieve directory information.
Solution: Changed the query to use left join instead of inner join when joining to table_fs_file_data. This ensures that directories are included in the results even without corresponding data entries on table_fs_file_data, preserving the kind field while allowing data-specific fields to be null where appropriate.
This change makes it possible to call `omni_vfs.file_info(fs, directory)` on any directory, not just root

Problem: omni_vfs.file_info for table_fs on root

---

cmake/PostgreSQLExtension.cmake
extensions/omni/CHANGELOG.md
extensions/omni/omni.c
versions.txt

Solution: don't wait for background worker startup in recovery _if_ the background worker is registered to be started after recovery is finished.
Added STANDBY env variable for running `psql_` targets in standby (recovery) mode.

Problem: omni_httpd locking up backend when used in recovery mode (🚀 omni 0.2.8)

---

extensions/omni_sqlite/CHANGELOG.md
extensions/omni_sqlite/omni_sqlite.cpp
extensions/omni_sqlite/tests/test.yaml

If a column starts with type TEXT but then becomes INTEGER, that's
undefined behavior – could return something that looks like a string (by
pure chance), or could crash the backend.
Solution: track and error out on type mismatch

Problem: omni_sqlite would crash on mixed return types

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/tests/role_change.yml

This is sometimes necessary because currently Postgres does not allow roles to be changed using `security definer` in procedures (as opposed to functions)
Soluton: ensure we reset the security context
to what it was before the change

Problem: using `set role` in omni_httpd handlers

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/tests/router.yml

When presented with no argument mode, it'll simply crash. Not good.
Solution: check if there's any argmode at all

Problem: httpd handler argument `omni_httpd.http_response` with no `out`

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/docs/security.md
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/migrate/13_handler_role.sql
extensions/omni_httpd/tests/role_change.yml

Problems start appearing when we try to use multi-transactional capabilities (the very reason we support procedures) as the case of security-definer procedures is not currently supported in Postgres.
Solution: introduce `handler_role` relation
This relation is external annotation of desires roles, as opposed to security definer.
We could have set this from security-definer procedure's owner information, but then `fmgr_security_definer` would kick in and modify the security context, which `StartTransaction` does not expect and will fail. So we're forced to externalize this.

Problem: can't use `security definer` procedures in omni_httpd

---

.github/workflows/docker.yml

Cache export fails:
```
ERROR: failed to solve: error writing layer blob: error committing cache 396840: Failed to commit cache.
```
Solution: avoid pinning buildx
Thanks to the @WarpBuilds team!

Problem: docker builds are failing on CI

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/http_worker.h
extensions/omni_httpd/migrate/14_handler_operations.sql
extensions/omni_httpd/omni_httpd.c
extensions/omni_httpd/src/stop_handling.sql
extensions/omni_httpd/tests/router_order.yml

Sometimes, a middleware handler should stop. For example, there's an error; or an access has been denied.
Solution: introduce `stop_handling()` function
This function tells the runner to stop handling the request after the completion of this handler and serve the response as is.

Problem: omni_httpd middleware handlers run to completion

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/tests/router_order.yml

If we need to change the response in any way after the handler was called, we can't really do much. This can be very useful for things like CORS handlers or anything that changes the response.
Solution: only stop processing "handlers" after one is executed but continue with the rest of middleware handlers
(We really should rename them to something more sensible – middleware "after" doesn't make sense logically)

Problem: after-handler middleware in omni_httpd

---

extensions/omni/CHANGELOG.md
extensions/omni/extension.c
extensions/omni/init.c
extensions/omni/test/tests/late_ext.yml

If there are two backends, A and B and then A installs an extension, it will not always be initialized (`_Omni_init`) in B.
This is a fairly critical bug.
Solution: ensure we track respective invalidations
In Postgres 18, EXTENSIONOID is a syscache. Prior to that, we'll use PROCOID syscache as a proxy with a workaround for extensions that export no functions.

Problem: loading extensions in presence of live backends

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/http_worker.c
extensions/omni_httpd/tests/router_null_outcome.yml

If non-first middleware nullifies `outcome`, omni_httpd worker crashes.
Solution: ensure we properly tracking nullity of outcome

Problem: middleware nullifying outcome

---

extensions/omni/CHANGELOG.md
extensions/omni/init.c
extensions/omni/workers.c

However, this wouldn't work for supporting extensions that need to operate in inconsistent state (such as in replicas).
Solution: switch to ConsistentState

Problem: omni starts working only when recovery is finished

---

extensions/omni_worker/CHANGELOG.md
extensions/omni_worker/deps/oink.hpp
versions.txt

```
In file included from /build/source/build/dep-bf2b3f73337260d99ddad54eaaa9c232c19ab69b/boost/interprocess/detail/managed_memory_impl.hpp:30:
/build/source/build/dep-bf2b3f73337260d99ddad54eaaa9c232c19ab69b/boost/interprocess/segment_manager.hpp:1055:41: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
1055 |          hdr = block_header_t::template from_first_header(reinterpret_cast<index_data_t*>((void*)((char*)buffer_ptr + front_space)));
|                                         ^
In file included from /build/source/extensions/omni_worker/handlers.cpp:2:
/build/source/extensions/omni_worker/deps/oink.hpp:156:12: error: object of type 'arena' cannot be assigned because its copy assignment …
```

Problem: omni_worker fails to compile on Nix

---

extensions/omni_ledger/migrate/1_core.sql
extensions/omni_ledger/tests/trigger_ordering.yaml

They occur in transactions that are not supposed to fail.
Solution: ensure we update balances first
If this doesn't happen, we have problems with:
1) actual reflected balances available to other triggers 2) interactions with the cache and our current marking for "touched"
accounts.
Our current system of account caches and computation of balances is fairly fragile and would benefit from a re-design (and a port to Cppgres).
This solution is a bit fragile as this depends on the naming-based order, but this fixes the problem for now before the next major revision is ready.

Problem: account categorization balancing failures (🚀 omni_ledger 0.1.3)

---

extensions/omni_httpd/CHANGELOG.md
extensions/omni_httpd/src/instantiate_static_file_handler.sql
extensions/omni_httpd/src/static_file_handler.sql
extensions/omni_httpd/tests/static_file.yml

Regardless of whether the client already has the file, the server will always resend it.
Solution: implement basic support for `ETag

Problem: HTTP static file server is not cache-efficient

---

README.md
extensions/omni_csv/CHANGELOG.md
extensions/omni_csv/CMakeLists.txt
extensions/omni_csv/README.md
extensions/omni_csv/deps/.clang-format
extensions/omni_csv/deps/cppgres.hpp
extensions/omni_csv/deps/csv.hpp
extensions/omni_csv/docs/index.md
extensions/omni_csv/migrate/1_init.sql
extensions/omni_csv/mkdocs.yml
extensions/omni_csv/omni_csv.cpp
extensions/omni_csv/src/instantiate.sql
extensions/omni_csv/tests/test.yml
versions.txt

On the surface, Postgres has good support for CSVs – but it is limited to the `COPY` commands, which are not as useful in a query context.
Solution: add omni_csv extension to the mix

Problem: processing data in CSV (🚀 omni_csv 0.1.0)

---

extensions/omni/CHANGELOG.md
extensions/omni/omni.c

It does not show details, like: `"name must be under 64 bytes long`:
Which name?
Solution: include more details

Problem: omni error reporting

---

extensions/omni_schema/CHANGELOG.md
extensions/omni_schema/docs/dump_restore.md
extensions/omni_schema/docs/reference.md
extensions/omni_schema/migrate/10_dump.sql
extensions/omni_schema/src/_validate_connstr.sql
extensions/omni_schema/src/dump.sql
extensions/omni_schema/src/restore.sql
extensions/omni_schema/tests/dump_restore.yml

While we can capture meta catalog, this takes time and is not guaranteed to be a full copy of the catalog.
Solution: allow capturing and restoring schema as SQL
This is done by calling pg_dump and psql externally.

Problem: capturing schemas in full

---

extensions/omni_schema/CHANGELOG.md
extensions/omni_schema/src/dump.sql

The schema file lines may be misordered.
Solution: ensure we capture their order
While at it, ensure we only have another unused character for `null`

Problem: omni_schema dump ordering may be incorrect

---

extensions/omni_kube/CHANGELOG.md
extensions/omni_kube/CMakeLists.txt
extensions/omni_kube/docs/credentials.md
extensions/omni_kube/docs/internals_api.md
extensions/omni_kube/docs/resources.md
extensions/omni_kube/mkdocs.yml
extensions/omni_kube/src/instantiate.sql
extensions/omni_kube/src/load_kubeconfig.sql

In-container credentials are picked up automatically but everything else is much harder.
Solution: introduce `load_kubeconfig` to simplify credentials

Problem: loading Kubernetes credentials

---

extensions/omni_kube/CHANGELOG.md
extensions/omni_kube/docs/resources.md
extensions/omni_kube/src/instantiate.sql
extensions/omni_kube/src/resource_table.sql
extensions/omni_kube/tests/test.yml

This is still fairly difficult. Resource views in omni_kube are helpful but they don't help managing state – they just represent what's there now.
Solution: add a concept of resource tables
These act as replicas and exhibit many properties of resource views (they are naturally updatable and the updates propagate back to Kubernetes), but they maintain a stable view that can be refreshed manually (or scheduled).
What's even more interesting is that they can be part of trigger cascades, enabling more logic to be embededded.
They are, however, not respecting the boundaries of transactions and changes are reflected in Kubernetes immediately.

Problem: developing Kubernetes operators/controllers

---

extensions/omni_kube/CHANGELOG.md
extensions/omni_kube/docs/internals_api.md
extensions/omni_kube/docs/paths.md
extensions/omni_kube/mkdocs.yml
extensions/omni_kube/src/api.sql
extensions/omni_kube/src/group_path.sql
extensions/omni_kube/src/group_resources.sql
extensions/omni_kube/src/instantiate.sql
extensions/omni_kube/src/path_with.sql
extensions/omni_kube/src/resource_table.sql
extensions/omni_kube/src/resource_view.sql
extensions/omni_kube/src/resources.sql
extensions/omni_kube/src/resources_path.sql
extensions/omni_kube/src/watch.sql
extensions/omni_kube/src/watch_path.sql

For example, api() special-cases things like fieldSelector and labelSelector and it's going to be hard to compose watches.
Solution: extract path helpers and make them composable

Problem: omni_kube API doesn't compose well

---

extensions/omni_kube/CHANGELOG.md
extensions/omni_kube/CMakeLists.txt
extensions/omni_kube/docs/resources.md
extensions/omni_kube/src/api.sql
extensions/omni_kube/src/path_with.sql
extensions/omni_kube/src/resource_table.sql
extensions/omni_kube/tests/transactional.yml

While it is not a huge issue, it is not perfect either – in some cases it is desirable to at least imitate some sort of transactional boundaries.
Solution: simulate read-committed isolation
by dry-running changes and pooling them up until commit time.

Problem: omni_kube resource tables aren't transactional

---

extensions/omni_worker/CHANGELOG.md
extensions/omni_worker/handlers.cpp
extensions/omni_worker/tests/sql.yml

Solution: ensure we return from sql handler after commit
We were sending the notification when we performed the statement, but
before we actually comitted it. It was causing tests to not see
committed data (because it wasn't yet!)

Problem: spurious failures in omni_worker sql tests

---

extensions/omni_worker/CHANGELOG.md
extensions/omni_worker/src/instantiate.sql
extensions/omni_worker/tests/sql_autostart.yml

They can find them by the statement itself, but this is rather
overboard.
Solution: introduce statement labels
Labels are made immutable so that users don't rename them

 Problem: how do users find their sql autostart statements?

---

extensions/omni_kube/tests/test.yml

Particularly, the list of resources in the core may differ.
Solution: limit the resources to be seen

Problem: omni_kube tests may fail on some setups
